/*********************************************************
 **
 ** File  SDY2_game_LED.c
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\LED.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2017-12-22T17:12:38
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY2_game\Code -prefix SDY2_game_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\game.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst
 *********************************************************/

/* Inlined constants:
   WL_BACK1=2
   WL_BACK3=4
   WL_LEGEND=15
   WL_WHITE=0
 */

#include "SDY2_game_LED.h"
#include "SDY2_game_imported_functions.h"
#include "sgl_simu.h"


#include <stdlib.h>
#include <string.h>

SDY2_game_typ_LED * SDY2_game_LED_alloc(void)
{
  SDY2_game_typ_LED *lContext = malloc(sizeof(SDY2_game_typ_LED));
  memset(lContext, 0L, sizeof(SDY2_game_typ_LED));
  return lContext;
}

void SDY2_game_LED_free(SDY2_game_typ_LED *pContext)
{
  free(pContext);
}


void SDY2_game_LED_init(SDY2_game_typ_LED *pContext)
{
  SDY2_game_LED_S_SizeX(pContext, 40.0F);
  SDY2_game_LED_S_SizeY(pContext, 40.0F);
  SDY2_game_LED_S_Style(pContext, 1L);
  SDY2_game_LED_S_ColorStyle(pContext, 0L);
  SDY2_game_LED_S_LEDOn(pContext, 0);
  SDY2_game_LED_S_LEDColor(pContext, 45L);
  {
    static SGLuint8 lArray0[255UL] = {76U,69U,68U};
    SDY2_game_LED_S_Legend(pContext, lArray0);
  }
  SDY2_game_LED_S_LegendColor(pContext, -1L);
  SDY2_game_LED_S_Font(pContext, 21L);
  SDY2_game_LED_S_BaseColor(pContext, 1000L);
  SDY2_game_LED_S_BorderThickness0(pContext, 5.0F);
  SDY2_game_LED_S_BorderThickness(pContext, 5.0F);

  pContext->_parentPriority = 0L;

}

void SDY2_game_LED_predraw(SDY2_game_typ_LED *pContext)
{
  SDY2_game_LED_S_BaseColor(pContext, 1000L);
  SDY2_game_LED_S_BorderThickness(pContext, 5.0F);

}

void SDY2_game_LED_draw(SDY2_game_typ_LED *pContext, SGLint32 pPriority)
{
  SGLuint32 _lParentMasks = f065();
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: LED, Type: container, OID: 037a9d2a-3b53-410f-a681-d92a6a482d35 */
    {

      /* Object: ColorBase, Type: referenceContainer, OID: ae06b395-bde7-43a9-a706-a0fd9939159a */
      {
        SDY2_game_typ_ColorBase _lSubContextVar;
        SDY2_game_typ_ColorBase *_lSubContext = &_lSubContextVar;
        SDY2_game_ColorBase_init(_lSubContext);
        SDY2_game_ColorBase_S_ColorStyle(_lSubContext, SDY2_game_LED_G_ColorStyle(pContext));
        _lSubContext->_parentPriority = pContext->_parentPriority;
        SDY2_game_ColorBase_draw(_lSubContext, pPriority);
        SDY2_game_LED_G_BaseColor(pContext) = SDY2_game_ColorBase_G_ColorBase(_lSubContext);
      }

      /* Object: BorderThickness0, Type: assignment, OID: 0487d584-7ba2-40d3-80f3-8a43e1e8154f */
      {
        SDY2_game_LED_G_BorderThickness0(pContext) = SGLfloat_div((SGLfloat_gt(SDY2_game_LED_G_SizeX(pContext), SDY2_game_LED_G_SizeY(pContext)) ? SDY2_game_LED_G_SizeY(pContext) : SDY2_game_LED_G_SizeX(pContext)), 8.0F);
      }

      /* Object: BorderThickness, Type: assignment, OID: c0a2ff9d-09f1-4082-8214-ffe4fef7a7c2 */
      {
        SDY2_game_LED_G_BorderThickness(pContext) = (SGLfloat_gt(SDY2_game_LED_G_BorderThickness0(pContext), 5.0F) ? 5.0F : SDY2_game_LED_G_BorderThickness0(pContext));
      }

      /* Object: Style, Type: conditional, OID: 9e655a02-19f4-437b-8fe7-99a38d9b0e2c */
      {
        switch (SDY2_game_LED_G_Style(pContext)) {

        case 2L:

          /* Object: RECT, Type: container, OID: 00f25dab-fce1-424b-ab84-3f414c73c33e */
          {

            /* Object: BorderOut_1, Type: referenceContainer, OID: 3f30ee97-f555-47a0-84c5-5dcf7a268e60 */
            {
              f056(_lParentMasks);
              {
                SDY2_game_typ_FrameShape _lSubContextVar;
                SDY2_game_typ_FrameShape *_lSubContext = &_lSubContextVar;
                SDY2_game_FrameShape_init(_lSubContext);
                SDY2_game_FrameShape_S_Color(_lSubContext, SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 2L));
                SDY2_game_FrameShape_S_Opacity(_lSubContext, 255L);
                SDY2_game_FrameShape_S_Orientation(_lSubContext, 0L);
                SDY2_game_FrameShape_S_OutlineColor(_lSubContext, SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 4L));
                SDY2_game_FrameShape_S_OutlineOpacity(_lSubContext, 255L);
                SDY2_game_FrameShape_S_OutlineRadius(_lSubContext, 8.0F);
                SDY2_game_FrameShape_S_OutlineWidth(_lSubContext, 0L);
                SDY2_game_FrameShape_S_SizeX(_lSubContext, SDY2_game_LED_G_SizeX(pContext));
                SDY2_game_FrameShape_S_SizeY(_lSubContext, SDY2_game_LED_G_SizeY(pContext));
                SDY2_game_FrameShape_S_Style(_lSubContext, 1L);
                SDY2_game_FrameShape_S_Texture(_lSubContext, -1L);
                _lSubContext->_parentPriority = pContext->_parentPriority;
                SDY2_game_FrameShape_draw(_lSubContext, pPriority);
              }
            }

            /* Object: BorderIn_1, Type: referenceContainer, OID: 70f9cf2f-4f38-4709-a605-b010787b6178 */
            {
              f056(_lParentMasks);
              {
                SDY2_game_typ_FrameShape _lSubContextVar;
                SDY2_game_typ_FrameShape *_lSubContext = &_lSubContextVar;
                SDY2_game_FrameShape_init(_lSubContext);
                SDY2_game_FrameShape_S_Color(_lSubContext, SDY2_game_LED_G_BaseColor(pContext));
                SDY2_game_FrameShape_S_Opacity(_lSubContext, 255L);
                SDY2_game_FrameShape_S_Orientation(_lSubContext, 0L);
                SDY2_game_FrameShape_S_OutlineColor(_lSubContext, SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 4L));
                SDY2_game_FrameShape_S_OutlineOpacity(_lSubContext, 255L);
                SDY2_game_FrameShape_S_OutlineRadius(_lSubContext, 8.0F);
                SDY2_game_FrameShape_S_OutlineWidth(_lSubContext, 0L);
                SDY2_game_FrameShape_S_SizeX(_lSubContext, SDY2_game_LED_G_SizeX(pContext));
                SDY2_game_FrameShape_S_SizeY(_lSubContext, SDY2_game_LED_G_SizeY(pContext));
                SDY2_game_FrameShape_S_Style(_lSubContext, 1L);
                SDY2_game_FrameShape_S_Texture(_lSubContext, 247L);
                _lSubContext->_parentPriority = pContext->_parentPriority;
                SDY2_game_FrameShape_draw(_lSubContext, pPriority);
              }
            }

            /* Object: Led_1, Type: referenceContainer, OID: 4612d6cd-b205-4ce3-8897-d847eb6c5afb */
            {
              f056(_lParentMasks);
              f073(SDY2_game_LED_G_BorderThickness(pContext), SDY2_game_LED_G_BorderThickness(pContext));
              {
                SDY2_game_typ_FrameShape _lSubContextVar;
                SDY2_game_typ_FrameShape *_lSubContext = &_lSubContextVar;
                SDY2_game_FrameShape_init(_lSubContext);
                if (SDY2_game_LED_G_LEDOn(pContext)) {
                  SDY2_game_FrameShape_S_Color(_lSubContext, SDY2_game_LED_G_LEDColor(pContext));
                }
                else {
                  SDY2_game_FrameShape_S_Color(_lSubContext, SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 4L));
                }
                SDY2_game_FrameShape_S_Opacity(_lSubContext, 255L);
                SDY2_game_FrameShape_S_Orientation(_lSubContext, 0L);
                if (SDY2_game_LED_G_LEDOn(pContext)) {
                  SDY2_game_FrameShape_S_OutlineColor(_lSubContext, SDY2_game_LED_G_LEDColor(pContext));
                }
                else {
                  SDY2_game_FrameShape_S_OutlineColor(_lSubContext, SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 4L));
                }
                SDY2_game_FrameShape_S_OutlineOpacity(_lSubContext, 255L);
                SDY2_game_FrameShape_S_OutlineRadius(_lSubContext, 8.0F);
                SDY2_game_FrameShape_S_OutlineWidth(_lSubContext, 0L);
                SDY2_game_FrameShape_S_SizeX(_lSubContext, SGLfloat_sub(SDY2_game_LED_G_SizeX(pContext), SGLfloat_mul(SDY2_game_LED_G_BorderThickness(pContext), 2.0F)));
                SDY2_game_FrameShape_S_SizeY(_lSubContext, SGLfloat_sub(SDY2_game_LED_G_SizeY(pContext), SGLfloat_mul(SDY2_game_LED_G_BorderThickness(pContext), 2.0F)));
                SDY2_game_FrameShape_S_Style(_lSubContext, 1L);
                SDY2_game_FrameShape_S_Texture(_lSubContext, -1L);
                _lSubContext->_parentPriority = pContext->_parentPriority;
                SDY2_game_FrameShape_draw(_lSubContext, pPriority);
              }
              f074();
            }

            /* Object: LedGrad_1, Type: referenceContainer, OID: 9b33dbc3-0cdd-41c9-b801-5f6ade3192bd */
            {
              f056(_lParentMasks);
              f073(SDY2_game_LED_G_BorderThickness(pContext), SDY2_game_LED_G_BorderThickness(pContext));
              {
                SDY2_game_typ_FrameShape _lSubContextVar;
                SDY2_game_typ_FrameShape *_lSubContext = &_lSubContextVar;
                SDY2_game_FrameShape_init(_lSubContext);
                SDY2_game_FrameShape_S_Color(_lSubContext, SDY2_game_LED_G_BaseColor(pContext));
                SDY2_game_FrameShape_S_Opacity(_lSubContext, 255L);
                SDY2_game_FrameShape_S_Orientation(_lSubContext, 0L);
                if (SDY2_game_LED_G_LEDOn(pContext)) {
                  SDY2_game_FrameShape_S_OutlineColor(_lSubContext, SDY2_game_LED_G_LEDColor(pContext));
                }
                else {
                  SDY2_game_FrameShape_S_OutlineColor(_lSubContext, SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 4L));
                }
                SDY2_game_FrameShape_S_OutlineOpacity(_lSubContext, 255L);
                SDY2_game_FrameShape_S_OutlineRadius(_lSubContext, 8.0F);
                SDY2_game_FrameShape_S_OutlineWidth(_lSubContext, 0L);
                SDY2_game_FrameShape_S_SizeX(_lSubContext, SGLfloat_sub(SDY2_game_LED_G_SizeX(pContext), SGLfloat_mul(2.0F, SDY2_game_LED_G_BorderThickness(pContext))));
                SDY2_game_FrameShape_S_SizeY(_lSubContext, SGLfloat_sub(SDY2_game_LED_G_SizeY(pContext), SGLfloat_mul(2.0F, SDY2_game_LED_G_BorderThickness(pContext))));
                SDY2_game_FrameShape_S_Style(_lSubContext, 1L);
                SDY2_game_FrameShape_S_Texture(_lSubContext, 253L);
                _lSubContext->_parentPriority = pContext->_parentPriority;
                SDY2_game_FrameShape_draw(_lSubContext, pPriority);
              }
              f074();
            }

            /* Object: ellipse_1, Type: ellipse, OID: baf9c924-2aca-4d5f-a488-3eae55fb631d */
            {
              f056(_lParentMasks);
              if (SGLint32_ge(SDY2_game_LED_G_BaseColor(pContext), 0L)) {
                /* color object part */
                f013(SDY2_game_LED_G_BaseColor(pContext));
                f009(f224);
                f008(f148);
                f036(80L);
                f009(f167);
                f009(f230);
                /* fill object part */
                f072(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_add(SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SGLfloat_div(SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SDY2_game_LED_G_BorderThickness(pContext)), 2.0F)), SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 5.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 10.0F), 0.0F, 360.0F, 1, f219);
              }
            }
          }
          break;

        default:
        /* case 1L */

          /* Object: ELLIPSE, Type: container, OID: 6165f552-cf22-4c10-a34b-0ef813d4f70a */
          {

            /* Object: BorderOut, Type: ellipse, OID: f9953cf0-41ac-49c7-84a6-bdc8812f3ed0 */
            {
              f056(_lParentMasks);
              if (SGLint32_ge(SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 2L), 0L)) {
                /* color object part */
                f013(SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 2L));
                f009(f224);
                f008(f148);
                f036(255L);
                f009(f167);
                f009(f230);
                /* fill object part */
                f072(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), 0.0F, 360.0F, 1, f219);
              }
              if (SGLint32_ge(SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 4L), 0L)) {
                /* outline object part */
                f009(f167);
                f013(SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 4L));
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f216);
                f036(255L);
                f072(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), 0.0F, 360.0F, 1, f220);
              }
            }

            /* Object: BorderIn, Type: ellipse, OID: 2645a4c4-42b1-4f9c-91e9-7de9c9d4a6a4 */
            {
              if (SGLint32_ge(SDY2_game_LED_G_BaseColor(pContext), 0L)) {
                /* color object part */
                f013(SDY2_game_LED_G_BaseColor(pContext));
                f008(f224);
                f008(f148);
                f036(255L);
              }
              else {
                f009(f224);
              }
              /* texture object part */
              f003(f167, 247L);
              {
                SGLfloat lX[2UL];
                SGLfloat lY[2UL];
                lX[0UL] = SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F));
                lY[0UL] = SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F));
                lX[1UL] = SGLfloat_add(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F));
                lY[1UL] = SGLfloat_add(SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F));
                f052(2UL, lX, lY, 1.0F, 1.0F, f205, f208);
              }
              f008(f167);
              f009(f230);
              /* fill object part */
              f072(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), 0.0F, 360.0F, 1, f219);
              if (SGLint32_ge(SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 4L), 0L)) {
                /* outline object part */
                f009(f167);
                f013(SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 4L));
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f216);
                f036(255L);
                f072(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), 0.0F, 360.0F, 1, f220);
              }
            }

            /* Object: Led, Type: ellipse, OID: 2cfc81d4-518c-4eb7-a5e6-afb17d6e6099 */
            {
              if (SGLint32_ge((SDY2_game_LED_G_LEDOn(pContext) ? SDY2_game_LED_G_LEDColor(pContext) : SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 4L)), 0L)) {
                /* color object part */
                f013((SDY2_game_LED_G_LEDOn(pContext) ? SDY2_game_LED_G_LEDColor(pContext) : SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 4L)));
                f009(f224);
                f008(f148);
                f036(255L);
                f009(f167);
                /* fill object part */
                f072(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SDY2_game_LED_G_BorderThickness(pContext)), SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SDY2_game_LED_G_BorderThickness(pContext)), 0.0F, 360.0F, 1, f219);
                /* outline object part */
                f009(f167);
                f013((SDY2_game_LED_G_LEDOn(pContext) ? SDY2_game_LED_G_LEDColor(pContext) : SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 4L)));
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f216);
                f036(255L);
                f072(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SDY2_game_LED_G_BorderThickness(pContext)), SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SDY2_game_LED_G_BorderThickness(pContext)), 0.0F, 360.0F, 1, f220);
              }
            }

            /* Object: LedGrad, Type: ellipse, OID: 9316d416-eb93-4487-9384-445e720770b4 */
            {
              if (SGLint32_ge(SDY2_game_LED_G_BaseColor(pContext), 0L)) {
                /* color object part */
                f013(SDY2_game_LED_G_BaseColor(pContext));
                f008(f224);
                f008(f148);
                f036(255L);
              }
              else {
                f009(f224);
              }
              /* texture object part */
              f003(f167, 253L);
              {
                SGLfloat lX[2UL];
                SGLfloat lY[2UL];
                lX[0UL] = SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SDY2_game_LED_G_BorderThickness(pContext)));
                lY[0UL] = SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SDY2_game_LED_G_BorderThickness(pContext)));
                lX[1UL] = SGLfloat_add(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SDY2_game_LED_G_BorderThickness(pContext)));
                lY[1UL] = SGLfloat_add(SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SDY2_game_LED_G_BorderThickness(pContext)));
                f052(2UL, lX, lY, 1.0F, 1.0F, f205, f208);
              }
              f008(f167);
              /* fill object part */
              f072(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SDY2_game_LED_G_BorderThickness(pContext)), SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SDY2_game_LED_G_BorderThickness(pContext)), 0.0F, 360.0F, 1, f219);
              if (SGLint32_ge((SDY2_game_LED_G_LEDOn(pContext) ? SDY2_game_LED_G_LEDColor(pContext) : SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 4L)), 0L)) {
                /* outline object part */
                f009(f167);
                f013((SDY2_game_LED_G_LEDOn(pContext) ? SDY2_game_LED_G_LEDColor(pContext) : SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 4L)));
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f216);
                f036(255L);
                f072(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SDY2_game_LED_G_BorderThickness(pContext)), SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SDY2_game_LED_G_BorderThickness(pContext)), 0.0F, 360.0F, 1, f220);
              }
            }

            /* Object: ellipse, Type: ellipse, OID: d4986ffa-759e-48f1-9ef2-972382e09509 */
            {
              if (SGLint32_ge(SDY2_game_LED_G_BaseColor(pContext), 0L)) {
                /* color object part */
                f013(SDY2_game_LED_G_BaseColor(pContext));
                f009(f224);
                f008(f148);
                f036(80L);
                f009(f167);
                /* fill object part */
                f072(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SGLfloat_add(SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SGLfloat_div(SGLfloat_sub(SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 2.0F), SDY2_game_LED_G_BorderThickness(pContext)), 2.0F)), SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 5.0F), SGLfloat_div(SDY2_game_LED_G_SizeY(pContext), 10.0F), 0.0F, 360.0F, 1, f219);
              }
            }
          }
          break;
        }
      }

      /* Object: Label, Type: container, OID: c0967e25-8ab6-4712-a5e3-0b9f16417eb2 */
      {
        f073(SGLfloat_div(SDY2_game_LED_G_SizeX(pContext), 2.0F), SDY2_game_LED_G_SizeY(pContext));

        /* Object: text, Type: text, OID: 422a80e3-a478-4ddb-91bf-c6f4fa164019 */
        {
          if (SGLuint8_ne((SDY2_game_LED_G_Legend(pContext))[0UL], 0U)) {
            f056(_lParentMasks);
            if (SGLint32_ge((SGLint32_eq(SDY2_game_LED_G_LegendColor(pContext), -1L) ? SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 15L) : SDY2_game_LED_G_LegendColor(pContext)), 0L)) {
              f013((SGLint32_eq(SDY2_game_LED_G_LegendColor(pContext), -1L) ? SGLint32_add(SDY2_game_LED_G_BaseColor(pContext), 15L) : SDY2_game_LED_G_LegendColor(pContext)));
              f085(-1L);
              f075(2L);
              f048(SDY2_game_LED_G_Font(pContext));
              f009(f150);
              f050(f205, f209);
              f034(0.0F, 5.0F, SDY2_game_LED_G_Legend(pContext), 255L);
            }
          }
        }
        f074();
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-12-22T17:12:38
 *********************************************************/

