/*********************************************************
 **
 ** File  SDY2_game_TextDisplay.h
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\TextDisplay.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2017-12-22T17:12:38
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY2_game\Code -prefix SDY2_game_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\game.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst
 *********************************************************/

#ifndef SDY2_GAME_TEXTDISPLAY_H
#define SDY2_GAME_TEXTDISPLAY_H

#include "sgl_types.h"
#include "kcg_assign.h"


/* Accessors */
#define SDY2_game_TextDisplay_G_Text(_C_) (*(_C_)->Text)
#define SDY2_game_TextDisplay_S_Text(_C_,_V_) (_C_)->Text = &(_V_)
#define SDY2_game_TextDisplay_G_TextColor(_C_) (_C_)->TextColor
#define SDY2_game_TextDisplay_S_TextColor(_C_,_V_) (_C_)->TextColor = (_V_)
#define SDY2_game_TextDisplay_G_Legend(_C_) (*(_C_)->Legend)
#define SDY2_game_TextDisplay_S_Legend(_C_,_V_) (_C_)->Legend = &(_V_)
#define SDY2_game_TextDisplay_G_LegendColor(_C_) (_C_)->LegendColor
#define SDY2_game_TextDisplay_S_LegendColor(_C_,_V_) (_C_)->LegendColor = (_V_)
#define SDY2_game_TextDisplay_G_Font(_C_) (_C_)->Font
#define SDY2_game_TextDisplay_S_Font(_C_,_V_) (_C_)->Font = (_V_)
#define SDY2_game_TextDisplay_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct SDY2_game_typ_TextDisplay_ {
  /* ------------------------- inputs --------------------------- */
  SGLuint8 (*Text)[255UL];
  SGLint32 TextColor;
  SGLuint8 (*Legend)[255UL];
  SGLint32 LegendColor;
  SGLint32 Font;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} SDY2_game_typ_TextDisplay;

/* Associated functions */
extern void SDY2_game_TextDisplay_init(SDY2_game_typ_TextDisplay *pContext);
extern void SDY2_game_TextDisplay_predraw(SDY2_game_typ_TextDisplay *pContext);
extern void SDY2_game_TextDisplay_draw(SDY2_game_typ_TextDisplay *pContext, SGLint32 pPriority);
extern SDY2_game_typ_TextDisplay * SDY2_game_TextDisplay_alloc(void);
extern void SDY2_game_TextDisplay_free(SDY2_game_typ_TextDisplay *pContext);

#endif /* SDY2_GAME_TEXTDISPLAY_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-12-22T17:12:38
 *********************************************************/

