/*********************************************************
 **
 ** File  SDY2_game_ColorBase.c
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\ColorBase.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2017-12-22T17:12:38
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY2_game\Code -prefix SDY2_game_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\game.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst
 *********************************************************/

/* Inlined constants:
   COLOR_TABLE_BASE=1000
   COLOR_TABLE_RANGE=20
 */

#include "SDY2_game_ColorBase.h"
#include "SDY2_game_imported_functions.h"
#include "sgl_simu.h"


#include <stdlib.h>
#include <string.h>

SDY2_game_typ_ColorBase * SDY2_game_ColorBase_alloc(void)
{
  SDY2_game_typ_ColorBase *lContext = malloc(sizeof(SDY2_game_typ_ColorBase));
  memset(lContext, 0L, sizeof(SDY2_game_typ_ColorBase));
  return lContext;
}

void SDY2_game_ColorBase_free(SDY2_game_typ_ColorBase *pContext)
{
  free(pContext);
}


void SDY2_game_ColorBase_init(SDY2_game_typ_ColorBase *pContext)
{
  SDY2_game_ColorBase_S_ColorStyle(pContext, 0L);
  SDY2_game_ColorBase_S_ColorBase(pContext, 0L);

  pContext->_parentPriority = 0L;

}

void SDY2_game_ColorBase_predraw(SDY2_game_typ_ColorBase *pContext)
{
  SDY2_game_ColorBase_S_ColorBase(pContext, 0L);

}

void SDY2_game_ColorBase_draw(SDY2_game_typ_ColorBase *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: group, Type: container, OID: 7c055362-b67a-4c7f-87f5-8d5791cd8dd7 */
    {

      /* Object: assignment, Type: assignment, OID: ffa0a63c-0ec3-4208-bc57-eeb42f6297aa */
      {
        SDY2_game_ColorBase_G_ColorBase(pContext) = SGLint32_add(1000L, SGLint32_mul(SDY2_game_ColorBase_G_ColorStyle(pContext), 20L));
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2017-12-22T17:12:38
 *********************************************************/

