/*********************************************************
 **
 ** File  SDY1_specification_Highlight.c
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Highlight.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2018-01-13T10:58:27
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY1_specification\Code -prefix SDY1_specification_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\InfiniteKnob.wgfx
 *********************************************************/

/* Inlined constants:
   HaloRadius=8.0
   HighlightColor=2
 */

#include "SDY1_specification_Highlight.h"
#include "SDY1_specification_imported_functions.h"
#include "sgl_simu.h"


#include <stdlib.h>
#include <string.h>

SDY1_specification_typ_Highlight * SDY1_specification_Highlight_alloc(void)
{
  SDY1_specification_typ_Highlight *lContext = malloc(sizeof(SDY1_specification_typ_Highlight));
  memset(lContext, 0L, sizeof(SDY1_specification_typ_Highlight));
  return lContext;
}

void SDY1_specification_Highlight_free(SDY1_specification_typ_Highlight *pContext)
{
  free(pContext);
}


void SDY1_specification_Highlight_init(SDY1_specification_typ_Highlight *pContext)
{
  SDY1_specification_Highlight_S_SizeX(pContext, 150.0F);
  SDY1_specification_Highlight_S_SizeY(pContext, 50.0F);
  SDY1_specification_Highlight_S_Highlight(pContext, 1);
  SDY1_specification_Highlight_S_Style(pContext, 1L);

  pContext->_parentPriority = 0L;

}

void SDY1_specification_Highlight_predraw(SDY1_specification_typ_Highlight *pContext)
{

}

void SDY1_specification_Highlight_draw(SDY1_specification_typ_Highlight *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: Highlight, Type: container, OID: e4ee95e1-fc38-4ace-96d2-f2decbd0bd62 */
    {
      if (SDY1_specification_Highlight_G_Highlight(pContext)) {

        /* Object: conditional_group, Type: conditional, OID: 4b9b7bb7-c44a-47cd-a2c8-916ba540382f */
        {
          switch (SDY1_specification_Highlight_G_Style(pContext)) {

          case 2L:

            /* Object: RND, Type: container, OID: df3e9751-d4cc-4745-a491-d99ed78ac3d0 */
            {

              /* Object: rectangle_5, Type: rectangle, OID: f985acd7-f347-4a29-bac5-57110baf881f */
              {
                /* color object part */
                f013(2L);
                f008(f224);
                f008(f148);
                f036(128L);
                /* texture object part */
                f003(f167, 240L);
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = 8.0F;
                  lY[0UL] = SDY1_specification_Highlight_G_SizeY(pContext);
                  lX[1UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F);
                  lY[1UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F);
                  f052(2UL, lX, lY, 1.0F, 1.0F, f206, f207);
                }
                f008(f167);
                f009(f230);
                /* fill object part */
                f009(f227);
                f001(f109);
                f067(8.0F, SDY1_specification_Highlight_G_SizeY(pContext), 1.0F, 1.0F);
                f067(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F), SDY1_specification_Highlight_G_SizeY(pContext), 1.0F, 1.0F);
                f067(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F), SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F), 1.0F, 0.0F);
                f067(8.0F, SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F), 1.0F, 0.0F);
                f002();
              }

              /* Object: shape, Type: shape, OID: 9d0dabd9-fa91-4160-9ebb-31917abe5552 */
              {
                /* color object part */
                f009(f148);
                /* texture object part */
                {
                  SGLfloat lX[4UL];
                  SGLfloat lY[4UL];
                  lX[0UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F);
                  lY[0UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F);
                  lX[1UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F);
                  lY[1UL] = SDY1_specification_Highlight_G_SizeY(pContext);
                  lX[2UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 2.64F);
                  lY[2UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 2.64F);
                  lX[3UL] = SDY1_specification_Highlight_G_SizeX(pContext);
                  lY[3UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F);
                  f052(4UL, lX, lY, 1.0F, 1.0F, f205, f208);
                }
                /* fill object part */
                f001(f109);
                f067(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F), SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F), 0.01F, 0.01F);
                f067(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F), SDY1_specification_Highlight_G_SizeY(pContext), 0.9F, 0.9F);
                f067(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 2.64F), SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 2.64F), 0.9F, 0.9F);
                f067(SDY1_specification_Highlight_G_SizeX(pContext), SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F), 0.9F, 0.9F);
                f002();
              }

              /* Object: rectangle_6, Type: rectangle, OID: 11e88c89-50a6-480e-8d60-bc715a9c2a7c */
              {
                /* color object part */
                f008(f148);
                /* texture object part */
                f003(f167, 245L);
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = SDY1_specification_Highlight_G_SizeX(pContext);
                  lY[0UL] = 8.0F;
                  lX[1UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F);
                  lY[1UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F);
                  f052(2UL, lX, lY, 1.0F, 1.0F, f205, f208);
                }
                /* fill object part */
                f001(f109);
                f067(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F, 0.99F, 0.01F);
                f067(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F), 8.0F, 0.01F, 0.01F);
                f067(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F), SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F), 0.01F, 0.99F);
                f067(SDY1_specification_Highlight_G_SizeX(pContext), SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F), 0.99F, 0.99F);
                f002();
              }

              /* Object: shape_1, Type: shape, OID: af835813-0f44-4f5c-a108-60c149709375 */
              {
                /* color object part */
                f009(f148);
                /* texture object part */
                f003(f167, 240L);
                {
                  SGLfloat lX[4UL];
                  SGLfloat lY[4UL];
                  lX[0UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F);
                  lY[0UL] = 8.0F;
                  lX[1UL] = SDY1_specification_Highlight_G_SizeX(pContext);
                  lY[1UL] = 8.0F;
                  lX[2UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 2.64F);
                  lY[2UL] = 2.64F;
                  lX[3UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F);
                  lY[3UL] = 0.0F;
                  f052(4UL, lX, lY, 1.0F, 1.0F, f205, f208);
                }
                /* fill object part */
                f001(f109);
                f067(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F), 8.0F, 0.01F, 0.01F);
                f067(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F, 0.9F, 0.9F);
                f067(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 2.64F), 2.64F, 0.9F, 0.9F);
                f067(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F), 0.0F, 0.9F, 0.9F);
                f002();
              }

              /* Object: rectangle_7, Type: rectangle, OID: 0a68e4a6-92d1-4a8f-a2e7-f008a3d04f8c */
              {
                /* color object part */
                /* texture object part */
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = 8.0F;
                  lY[0UL] = 0.0F;
                  lX[1UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F);
                  lY[1UL] = 8.0F;
                  f052(2UL, lX, lY, 1.0F, 1.0F, f206, f207);
                }
                /* fill object part */
                f001(f109);
                f067(8.0F, 0.0F, 0.0F, 1.0F);
                f067(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F), 0.0F, 0.0F, 1.0F);
                f067(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F), 8.0F, 0.0F, 0.0F);
                f067(8.0F, 8.0F, 0.0F, 0.0F);
                f002();
              }

              /* Object: shape_2, Type: shape, OID: a5de5cb3-265a-49ff-b41e-3afa06ce4d7b */
              {
                /* color object part */
                /* texture object part */
                {
                  SGLfloat lX[4UL];
                  SGLfloat lY[4UL];
                  lX[0UL] = 8.0F;
                  lY[0UL] = 8.0F;
                  lX[1UL] = 8.0F;
                  lY[1UL] = 0.0F;
                  lX[2UL] = 2.64F;
                  lY[2UL] = 2.64F;
                  lX[3UL] = 0.0F;
                  lY[3UL] = 8.0F;
                  f052(4UL, lX, lY, 1.0F, 1.0F, f205, f208);
                }
                /* fill object part */
                f001(f109);
                f067(8.0F, 8.0F, 0.01F, 0.01F);
                f067(8.0F, 0.0F, 0.9F, 0.9F);
                f067(2.64F, 2.64F, 0.9F, 0.9F);
                f067(0.0F, 8.0F, 0.9F, 0.9F);
                f002();
              }

              /* Object: rectangle_8, Type: rectangle, OID: 77d594ec-cd6a-4843-896c-0d0173379b45 */
              {
                /* color object part */
                f008(f148);
                /* texture object part */
                f003(f167, 245L);
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = 0.0F;
                  lY[0UL] = 8.0F;
                  lX[1UL] = 8.0F;
                  lY[1UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F);
                  f052(2UL, lX, lY, 1.0F, 1.0F, f206, f207);
                }
                /* fill object part */
                f001(f109);
                f067(0.0F, 8.0F, 0.99F, 0.01F);
                f067(8.0F, 8.0F, 0.01F, 0.01F);
                f067(8.0F, SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F), 0.01F, 0.99F);
                f067(0.0F, SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F), 0.99F, 0.99F);
                f002();
              }

              /* Object: shape_3, Type: shape, OID: 78ea316f-2b40-46d7-afd6-2d2a6ad7599c */
              {
                /* color object part */
                f009(f148);
                /* texture object part */
                f003(f167, 240L);
                {
                  SGLfloat lX[4UL];
                  SGLfloat lY[4UL];
                  lX[0UL] = 8.0F;
                  lY[0UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F);
                  lX[1UL] = 0.0F;
                  lY[1UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F);
                  lX[2UL] = 2.64F;
                  lY[2UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 2.64F);
                  lX[3UL] = 8.0F;
                  lY[3UL] = SDY1_specification_Highlight_G_SizeY(pContext);
                  f052(4UL, lX, lY, 1.0F, 1.0F, f205, f208);
                }
                /* fill object part */
                f001(f109);
                f067(8.0F, SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F), 0.01F, 0.01F);
                f067(0.0F, SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F), 0.9F, 0.9F);
                f067(2.64F, SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 2.64F), 0.9F, 0.9F);
                f067(8.0F, SDY1_specification_Highlight_G_SizeY(pContext), 0.9F, 0.9F);
                f002();
              }

              /* Object: shape_4, Type: shape, OID: 21a9360c-916e-484a-9817-58dc3b4d9585 */
              {
                /* outline object part */
                f009(f167);
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f216);
                f001(f103);
                f035(0.0F, 8.0F);
                f035(0.0F, SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F));
                f035(2.64F, SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 2.64F));
                f035(8.0F, SDY1_specification_Highlight_G_SizeY(pContext));
                f035(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F), SDY1_specification_Highlight_G_SizeY(pContext));
                f035(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 2.64F), SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 2.64F));
                f035(SDY1_specification_Highlight_G_SizeX(pContext), SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F));
                f035(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F);
                f035(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 2.64F), 2.64F);
                f035(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F), 0.0F);
                f035(8.0F, 0.0F);
                f035(2.64F, 2.64F);
                f002();
              }
            }
            break;

          case 3L:

            /* Object: ELLIPSE, Type: container, OID: 3d58efe7-0900-42a7-b9f4-34a2394e9ede */
            {

              /* Object: Center, Type: container, OID: a1f49141-efa8-4d38-8827-708f14c4deb2 */
              {
                f073(SGLfloat_div(SDY1_specification_Highlight_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY1_specification_Highlight_G_SizeY(pContext), 2.0F));

                /* Object: shape_5, Type: shape, OID: 86c19833-5361-47c8-8406-fb62198748ba */
                {
                  /* color object part */
                  f013(2L);
                  f008(f224);
                  f009(f148);
                  f036(128L);
                  /* texture object part */
                  f003(f167, 251L);
                  {
                    SGLfloat lX[4UL];
                    SGLfloat lY[4UL];
                    lX[0UL] = 0.0F;
                    lY[0UL] = 0.0F;
                    lX[1UL] = SGLfloat_div(SDY1_specification_Highlight_G_SizeX(pContext), 2.0F);
                    lY[1UL] = 0.0F;
                    lX[2UL] = SGLfloat_div(SDY1_specification_Highlight_G_SizeX(pContext), 2.0F);
                    lY[2UL] = SGLfloat_div(SDY1_specification_Highlight_G_SizeY(pContext), 2.0F);
                    lX[3UL] = 0.0F;
                    lY[3UL] = SGLfloat_div(SDY1_specification_Highlight_G_SizeY(pContext), 2.0F);
                    f052(4UL, lX, lY, 1.0F, 1.0F, f205, f208);
                  }
                  f008(f167);
                  f009(f230);
                  /* fill object part */
                  f009(f227);
                  f001(f109);
                  f067(0.0F, 0.0F, 0.03F, 0.97F);
                  f067(SGLfloat_div(SDY1_specification_Highlight_G_SizeX(pContext), 2.0F), 0.0F, 0.97F, 0.97F);
                  f067(SGLfloat_div(SDY1_specification_Highlight_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY1_specification_Highlight_G_SizeY(pContext), 2.0F), 0.97F, 0.03F);
                  f067(0.0F, SGLfloat_div(SDY1_specification_Highlight_G_SizeY(pContext), 2.0F), 0.03F, 0.03F);
                  f002();
                }

                /* Object: shape_6, Type: shape, OID: fcc65bc3-1d89-4055-a6a2-4ed91ab333a1 */
                {
                  /* color object part */
                  /* texture object part */
                  {
                    SGLfloat lX[4UL];
                    SGLfloat lY[4UL];
                    lX[0UL] = 0.0F;
                    lY[0UL] = 0.0F;
                    lX[1UL] = SGLfloat_div(SDY1_specification_Highlight_G_SizeX(pContext), 2.0F);
                    lY[1UL] = 0.0F;
                    lX[2UL] = SGLfloat_div(SDY1_specification_Highlight_G_SizeX(pContext), 2.0F);
                    lY[2UL] = SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeY(pContext)), 2.0F);
                    lX[3UL] = 0.0F;
                    lY[3UL] = SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeY(pContext)), 2.0F);
                    f052(4UL, lX, lY, 1.0F, 1.0F, f205, f208);
                  }
                  /* fill object part */
                  f001(f109);
                  f067(0.0F, 0.0F, 0.03F, 0.97F);
                  f067(SGLfloat_div(SDY1_specification_Highlight_G_SizeX(pContext), 2.0F), 0.0F, 0.97F, 0.97F);
                  f067(SGLfloat_div(SDY1_specification_Highlight_G_SizeX(pContext), 2.0F), SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeY(pContext)), 2.0F), 0.97F, 0.03F);
                  f067(0.0F, SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeY(pContext)), 2.0F), 0.03F, 0.03F);
                  f002();
                }

                /* Object: shape_7, Type: shape, OID: 4d95e023-0754-4a30-aabf-f3b6f76a6727 */
                {
                  /* color object part */
                  /* texture object part */
                  {
                    SGLfloat lX[4UL];
                    SGLfloat lY[4UL];
                    lX[0UL] = 0.0F;
                    lY[0UL] = 0.0F;
                    lX[1UL] = 0.0F;
                    lY[1UL] = SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeY(pContext)), 2.0F);
                    lX[2UL] = SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeX(pContext)), 2.0F);
                    lY[2UL] = SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeY(pContext)), 2.0F);
                    lX[3UL] = SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeX(pContext)), 2.0F);
                    lY[3UL] = 0.0F;
                    f052(4UL, lX, lY, 1.0F, 1.0F, f205, f208);
                  }
                  /* fill object part */
                  f001(f109);
                  f067(0.0F, 0.0F, 0.03F, 0.97F);
                  f067(0.0F, SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeY(pContext)), 2.0F), 0.97F, 0.97F);
                  f067(SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeX(pContext)), 2.0F), SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeY(pContext)), 2.0F), 0.97F, 0.03F);
                  f067(SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeX(pContext)), 2.0F), 0.0F, 0.03F, 0.03F);
                  f002();
                }

                /* Object: shape_8, Type: shape, OID: dcf118b2-4e4b-48c2-b497-b438fafba7dd */
                {
                  /* color object part */
                  /* texture object part */
                  {
                    SGLfloat lX[4UL];
                    SGLfloat lY[4UL];
                    lX[0UL] = 0.0F;
                    lY[0UL] = 0.0F;
                    lX[1UL] = SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeX(pContext)), 2.0F);
                    lY[1UL] = 0.0F;
                    lX[2UL] = SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeX(pContext)), 2.0F);
                    lY[2UL] = SGLfloat_div(SDY1_specification_Highlight_G_SizeY(pContext), 2.0F);
                    lX[3UL] = 0.0F;
                    lY[3UL] = SGLfloat_div(SDY1_specification_Highlight_G_SizeY(pContext), 2.0F);
                    f052(4UL, lX, lY, 1.0F, 1.0F, f205, f208);
                  }
                  /* fill object part */
                  f001(f109);
                  f067(0.0F, 0.0F, 0.03F, 0.97F);
                  f067(SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeX(pContext)), 2.0F), 0.0F, 0.97F, 0.97F);
                  f067(SGLfloat_div(SGLfloat_neg(SDY1_specification_Highlight_G_SizeX(pContext)), 2.0F), SGLfloat_div(SDY1_specification_Highlight_G_SizeY(pContext), 2.0F), 0.97F, 0.03F);
                  f067(0.0F, SGLfloat_div(SDY1_specification_Highlight_G_SizeY(pContext), 2.0F), 0.03F, 0.03F);
                  f002();
                }

                /* Object: ellipse, Type: ellipse, OID: ef6dc671-9a41-42d2-b198-bb53d6fa5267 */
                {
                  /* outline object part */
                  f009(f167);
                  f085(-1L);
                  f015(0L);
                  f014(0L);
                  f009(f150);
                  f068(f216);
                  f072(0.0F, 0.0F, SGLfloat_add(SGLfloat_div(SDY1_specification_Highlight_G_SizeX(pContext), 2.0F), 1.0F), SGLfloat_add(SGLfloat_div(SDY1_specification_Highlight_G_SizeY(pContext), 2.0F), 1.0F), 0.0F, 360.0F, 1, f220);
                }
                f074();
              }
            }
            break;

          default:
          /* case 1L */

            /* Object: RECT, Type: container, OID: 277284ed-81be-4acd-a221-314392893fb9 */
            {

              /* Object: rectangle, Type: rectangle, OID: e7e76099-786d-48d2-91ef-e22c6277496b */
              {
                /* color object part */
                f013(2L);
                f008(f224);
                f009(f148);
                f036(128L);
                /* texture object part */
                f003(f167, 240L);
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = 0.0F;
                  lY[0UL] = SDY1_specification_Highlight_G_SizeY(pContext);
                  lX[1UL] = SDY1_specification_Highlight_G_SizeX(pContext);
                  lY[1UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F);
                  f052(2UL, lX, lY, 1.0F, 1.0F, f206, f207);
                }
                f008(f167);
                f009(f230);
                /* fill object part */
                f009(f227);
                f001(f109);
                f067(0.0F, SDY1_specification_Highlight_G_SizeY(pContext), 0.0F, 1.0F);
                f067(SDY1_specification_Highlight_G_SizeX(pContext), SDY1_specification_Highlight_G_SizeY(pContext), 1.0F, 1.0F);
                f067(SDY1_specification_Highlight_G_SizeX(pContext), SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F), 1.0F, 0.0F);
                f067(0.0F, SGLfloat_sub(SDY1_specification_Highlight_G_SizeY(pContext), 8.0F), 0.0F, 0.0F);
                f002();
              }

              /* Object: rectangle_1, Type: rectangle, OID: fe202011-ef75-41d1-a0e9-f18399866507 */
              {
                /* color object part */
                /* texture object part */
                f003(f167, 245L);
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = SDY1_specification_Highlight_G_SizeX(pContext);
                  lY[0UL] = 0.0F;
                  lX[1UL] = SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F);
                  lY[1UL] = SDY1_specification_Highlight_G_SizeY(pContext);
                  f052(2UL, lX, lY, 1.0F, 1.0F, f205, f208);
                }
                /* fill object part */
                f001(f109);
                f067(SDY1_specification_Highlight_G_SizeX(pContext), 0.0F, 0.99F, 0.01F);
                f067(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F), 0.0F, 0.01F, 0.01F);
                f067(SGLfloat_sub(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F), SDY1_specification_Highlight_G_SizeY(pContext), 0.01F, 0.01F);
                f067(SDY1_specification_Highlight_G_SizeX(pContext), SDY1_specification_Highlight_G_SizeY(pContext), 0.99F, 0.01F);
                f002();
              }

              /* Object: rectangle_2, Type: rectangle, OID: 3f4a7ebc-d4e7-44b7-a941-8e9c19956137 */
              {
                /* color object part */
                /* texture object part */
                f003(f167, 240L);
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = 0.0F;
                  lY[0UL] = 0.0F;
                  lX[1UL] = SDY1_specification_Highlight_G_SizeX(pContext);
                  lY[1UL] = 8.0F;
                  f052(2UL, lX, lY, 1.0F, 1.0F, f206, f207);
                }
                /* fill object part */
                f001(f109);
                f067(0.0F, 0.0F, 0.0F, 1.0F);
                f067(SDY1_specification_Highlight_G_SizeX(pContext), 0.0F, 0.0F, 1.0F);
                f067(SDY1_specification_Highlight_G_SizeX(pContext), 8.0F, 0.0F, 0.0F);
                f067(0.0F, 8.0F, 0.0F, 0.0F);
                f002();
              }

              /* Object: rectangle_3, Type: rectangle, OID: 7273c7ec-2282-4a4d-9e96-fd7ea955e55c */
              {
                /* color object part */
                /* texture object part */
                f003(f167, 245L);
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = 0.0F;
                  lY[0UL] = 0.0F;
                  lX[1UL] = 8.0F;
                  lY[1UL] = SDY1_specification_Highlight_G_SizeY(pContext);
                  f052(2UL, lX, lY, 1.0F, 1.0F, f206, f207);
                }
                /* fill object part */
                f001(f109);
                f067(0.0F, 0.0F, 0.99F, 0.01F);
                f067(8.0F, 0.0F, 0.01F, 0.01F);
                f067(8.0F, SDY1_specification_Highlight_G_SizeY(pContext), 0.01F, 0.01F);
                f067(0.0F, SDY1_specification_Highlight_G_SizeY(pContext), 0.99F, 0.01F);
                f002();
              }

              /* Object: rectangle_4, Type: rectangle, OID: a90e9543-0e96-42c7-9cba-5e6df4e58007 */
              {
                /* outline object part */
                f009(f167);
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f216);
                f001(f103);
                f035(0.0F, 0.0F);
                f035(SDY1_specification_Highlight_G_SizeX(pContext), 0.0F);
                f035(SDY1_specification_Highlight_G_SizeX(pContext), SDY1_specification_Highlight_G_SizeY(pContext));
                f035(0.0F, SDY1_specification_Highlight_G_SizeY(pContext));
                f002();
              }
            }
            break;
          }
        }
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2018-01-13T10:58:27
 *********************************************************/

