/*********************************************************
 **
 ** File  SDY1_specification_line_stipple_table.c
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2018-01-13T10:58:28
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY1_specification\Code -prefix SDY1_specification_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\InfiniteKnob.wgfx
 *********************************************************/

#include "SDY1_specification_line_stipple_table.h"

/* Line stipple table definition */
const sgl_linestipple SDY1_specification_line_stipple_table[SDY1_specification_line_stipple_table_size] = 
{
{ {   0U,   0U,   0U,   0U,   0U,   0U}, {   0U,   0U,   0U,   0U,   0U,   0U},   1U,   0U}, /* 0 solid pattern : FullLine */
{ {  12U,  12U,   0U,   0U,   0U,   0U}, {   1U,   0U,   0U,   0U,   0U,   0U},   0U,   2U}, /* 1 dashed pattern :  */
{ {   8U,   8U,   0U,   0U,   0U,   0U}, {   1U,   0U,   0U,   0U,   0U,   0U},   0U,   2U}, /* 2 dashed pattern :  */
{ {   1U,   6U,   0U,   0U,   0U,   0U}, {   1U,   0U,   0U,   0U,   0U,   0U},   0U,   2U}, /* 3 dashed pattern :  */
{ {   1U,   8U,   8U,   8U,   0U,   0U}, {   1U,   0U,   1U,   0U,   0U,   0U},   0U,   4U}, /* 4 dashed pattern :  */
{ {   1U,   2U,   0U,   0U,   0U,   0U}, {   1U,   0U,   0U,   0U,   0U,   0U},   0U,   2U}, /* 5 dashed pattern : TreeBranch */
{ {   0U,   0U,   0U,   0U,   0U,   0U}, {   0U,   0U,   0U,   0U,   0U,   0U},   1U,   0U}, /* 6 solid pattern : Spare */
{ {   0U,   0U,   0U,   0U,   0U,   0U}, {   0U,   0U,   0U,   0U,   0U,   0U},   1U,   0U}, /* 7 solid pattern : Spare */
{ {   0U,   0U,   0U,   0U,   0U,   0U}, {   0U,   0U,   0U,   0U,   0U,   0U},   1U,   0U}, /* 8 solid pattern : Spare */
{ {   0U,   0U,   0U,   0U,   0U,   0U}, {   0U,   0U,   0U,   0U,   0U,   0U},   1U,   0U}, /* 9 solid pattern : Spare */
{ {   0U,   0U,   0U,   0U,   0U,   0U}, {   0U,   0U,   0U,   0U,   0U,   0U},   1U,   0U}, /* 10 solid pattern : Spare */
{ {   0U,   0U,   0U,   0U,   0U,   0U}, {   0U,   0U,   0U,   0U,   0U,   0U},   1U,   0U}, /* 11 solid pattern : Spare */
{ {   0U,   0U,   0U,   0U,   0U,   0U}, {   0U,   0U,   0U,   0U,   0U,   0U},   1U,   0U}, /* 12 solid pattern : Spare */
{ {   0U,   0U,   0U,   0U,   0U,   0U}, {   0U,   0U,   0U,   0U,   0U,   0U},   1U,   0U}, /* 13 solid pattern : Spare */
{ {   0U,   0U,   0U,   0U,   0U,   0U}, {   0U,   0U,   0U,   0U,   0U,   0U},   1U,   0U}, /* 14 solid pattern : Spare */
{ {   0U,   0U,   0U,   0U,   0U,   0U}, {   0U,   0U,   0U,   0U,   0U,   0U},   1U,   0U}  /* 15 solid pattern : Spare */
};

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-13T10:58:28
 *********************************************************/

