/*********************************************************
 **
 ** File  SDY1_specification_Cursor.c
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Cursor.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2018-01-13T10:58:27
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY1_specification\Code -prefix SDY1_specification_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\InfiniteKnob.wgfx
 *********************************************************/

#include "SDY1_specification_Cursor.h"
#include "SDY1_specification_imported_functions.h"
#include "sgl_simu.h"


#include <stdlib.h>
#include <string.h>

SDY1_specification_typ_Cursor * SDY1_specification_Cursor_alloc(void)
{
  SDY1_specification_typ_Cursor *lContext = malloc(sizeof(SDY1_specification_typ_Cursor));
  memset(lContext, 0L, sizeof(SDY1_specification_typ_Cursor));
  return lContext;
}

void SDY1_specification_Cursor_free(SDY1_specification_typ_Cursor *pContext)
{
  free(pContext);
}


void SDY1_specification_Cursor_init(SDY1_specification_typ_Cursor *pContext)
{
  SDY1_specification_Cursor_S_AreaSizeX(pContext, 0.0F);
  SDY1_specification_Cursor_S_AreaSizeY(pContext, 0.0F);
  {
    static SGLuint8 lArray0[255UL] = {0U};
    SDY1_specification_Cursor_S_String(pContext, lArray0);
  }
  SDY1_specification_Cursor_S_HorizontalAlignment(pContext, 0L);
  SDY1_specification_Cursor_S_CharIndex(pContext, 0L);
  SDY1_specification_Cursor_S_Font(pContext, 0L);
  SDY1_specification_Cursor_S_EnablePositionComputation(pContext, 0);
  SDY1_specification_Cursor_S_CursorVisibility(pContext, 0);
  SDY1_specification_Cursor_S_ClickedPositionX(pContext, 0.0F);
  SDY1_specification_Cursor_S_ClickedPositionY(pContext, 0.0F);
  SDY1_specification_Cursor_S_NewClick(pContext, 0);
  SDY1_specification_Cursor_S_EnableLineSizeComputation(pContext, 0);
  SDY1_specification_Cursor_S_TextColor(pContext, 2L);
  SDY1_specification_Cursor_S_CursorPosY(pContext, -20.0F);
  SDY1_specification_Cursor_S_NewIndexAfterClick(pContext, 0L);
  SDY1_specification_Cursor_S_LineFull(pContext, 0);
  SDY1_specification_Cursor_S_LineSizeX(pContext, 0.0F);
  SDY1_specification_Cursor_S_LineSizeY(pContext, 10.0F);
  SDY1_specification_Cursor_S_NbLines(pContext, 0L);
  SDY1_specification_Cursor_S_CursorPosX(pContext, 20.0F);
  SDY1_specification_Cursor_S_CharSize(pContext, 10.0F);
  SDY1_specification_Cursor_S_FontSizeX(pContext, 0.0F);
  SDY1_specification_Cursor_S_FontSizeY(pContext, 0.0F);

  pContext->_parentPriority = 0L;

}

void SDY1_specification_Cursor_predraw(SDY1_specification_typ_Cursor *pContext)
{
  SDY1_specification_Cursor_S_CursorPosY(pContext, -20.0F);
  SDY1_specification_Cursor_S_NewIndexAfterClick(pContext, 0L);
  SDY1_specification_Cursor_S_LineFull(pContext, 0);
  SDY1_specification_Cursor_S_LineSizeY(pContext, 10.0F);
  SDY1_specification_Cursor_S_NbLines(pContext, 0L);
  SDY1_specification_Cursor_S_CursorPosX(pContext, 20.0F);

}

void SDY1_specification_Cursor_draw(SDY1_specification_typ_Cursor *pContext, SGLint32 pPriority)
{
  SGLuint32 _lParentMasks = f065();
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: Cursor, Type: container, OID: 6dc182f3-d59c-4b95-a867-33cf83eda51c */
    {

      /* Object: CursorBehavior, Type: importedFunction, OID: 27c205b2-82b7-43fe-b6d9-c8ff8df93049 */
      {
        f019();
        CursorBehavior(SDY1_specification_Cursor_G_EnablePositionComputation(pContext), SDY1_specification_Cursor_G_EnableLineSizeComputation(pContext), SDY1_specification_Cursor_G_AreaSizeX(pContext), SDY1_specification_Cursor_G_AreaSizeY(pContext), SDY1_specification_Cursor_G_String(pContext), SDY1_specification_Cursor_G_CharIndex(pContext), SDY1_specification_Cursor_G_Font(pContext), SDY1_specification_Cursor_G_ClickedPositionX(pContext), SDY1_specification_Cursor_G_ClickedPositionY(pContext), SDY1_specification_Cursor_G_NewClick(pContext), SDY1_specification_Cursor_G_HorizontalAlignment(pContext), &(SDY1_specification_Cursor_G_CursorPosX(pContext)), &(SDY1_specification_Cursor_G_CursorPosY(pContext)), &(SDY1_specification_Cursor_G_LineFull(pContext)), &(SDY1_specification_Cursor_G_LineSizeX(pContext)), &(SDY1_specification_Cursor_G_LineSizeY(pContext)), &(SDY1_specification_Cursor_G_NbLines(pContext)), &(SDY1_specification_Cursor_G_CharSize(pContext)), &(SDY1_specification_Cursor_G_NewIndexAfterClick(pContext)));
        f064();
        f020();
      }

      /* Object: GetFontSize_Strings, Type: importedFunction, OID: 0a029430-c7ce-402b-9890-5d1ddf95e75d */
      {
        f056(_lParentMasks);
        f019();
        GetFontSize_Strings(0L, &(SDY1_specification_Cursor_G_FontSizeX(pContext)), &(SDY1_specification_Cursor_G_FontSizeY(pContext)));
        f064();
        f020();
      }

      /* Object: Cursor_1, Type: container, OID: f632d7c1-0d1d-4141-aa95-267ea2e19e76 */
      {
        if (SDY1_specification_Cursor_G_CursorVisibility(pContext)) {
          f073(SDY1_specification_Cursor_G_CursorPosX(pContext), SDY1_specification_Cursor_G_CursorPosY(pContext));

          /* Object: line, Type: line, OID: cad89664-141c-4b4c-97db-508e6515f53a */
          {
            f056(_lParentMasks);
            if (SGLint32_ge(SDY1_specification_Cursor_G_TextColor(pContext), 0L)) {
              /* outline object part */
              f009(f167);
              f013(SDY1_specification_Cursor_G_TextColor(pContext));
              f085(-1L);
              f015(1L);
              f014(0L);
              f009(f150);
              f068(f216);
              f036(255L);
              f001(f101);
              f035(0.0F, 0.0F);
              f035(0.0F, SGLfloat_mul(SDY1_specification_Cursor_G_FontSizeY(pContext), 1.5F));
              f002();
            }
          }

          /* Object: line_1, Type: line, OID: 98c6a89d-ed77-416d-a155-0623343101c8 */
          {
            if (SGLint32_ge(SDY1_specification_Cursor_G_TextColor(pContext), 0L)) {
              /* outline object part */
              f009(f167);
              f013(SDY1_specification_Cursor_G_TextColor(pContext));
              f085(-1L);
              f015(1L);
              f014(0L);
              f009(f150);
              f068(f216);
              f036(255L);
              f001(f101);
              f035(SGLfloat_div(SGLfloat_neg(SDY1_specification_Cursor_G_FontSizeX(pContext)), 4.0F), SGLfloat_mul(SDY1_specification_Cursor_G_FontSizeY(pContext), 1.5F));
              f035(SGLfloat_div(SDY1_specification_Cursor_G_FontSizeX(pContext), 4.0F), SGLfloat_mul(SDY1_specification_Cursor_G_FontSizeY(pContext), 1.5F));
              f002();
            }
          }

          /* Object: line_2, Type: line, OID: 9153b56d-5113-40ce-aa05-ad42004be068 */
          {
            if (SGLint32_ge(SDY1_specification_Cursor_G_TextColor(pContext), 0L)) {
              /* outline object part */
              f009(f167);
              f013(SDY1_specification_Cursor_G_TextColor(pContext));
              f085(-1L);
              f015(1L);
              f014(0L);
              f009(f150);
              f068(f216);
              f036(255L);
              f001(f101);
              f035(SGLfloat_div(SGLfloat_neg(SDY1_specification_Cursor_G_FontSizeX(pContext)), 4.0F), 0.0F);
              f035(SGLfloat_div(SDY1_specification_Cursor_G_FontSizeX(pContext), 4.0F), 0.0F);
              f002();
            }
          }
          f074();
        }
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2018-01-13T10:58:27
 *********************************************************/

