/*********************************************************
 **
 ** File  SDY1_specification_ColorBase.h
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\ColorBase.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2018-01-13T10:58:25
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY1_specification\Code -prefix SDY1_specification_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\InfiniteKnob.wgfx
 *********************************************************/

/* Inlined constants:
   COLOR_TABLE_BASE=1000
   COLOR_TABLE_RANGE=20
 */

#ifndef SDY1_SPECIFICATION_COLORBASE_H
#define SDY1_SPECIFICATION_COLORBASE_H

#include "sgl_types.h"


/* Accessors */
#define SDY1_specification_ColorBase_G_ColorStyle(_C_) (_C_)->ColorStyle
#define SDY1_specification_ColorBase_S_ColorStyle(_C_,_V_) (_C_)->ColorStyle = (_V_)
#define SDY1_specification_ColorBase_G_ColorBase(_C_) (_C_)->ColorBase
#define SDY1_specification_ColorBase_S_ColorBase(_C_,_V_) (_C_)->ColorBase = (_V_)
#define SDY1_specification_ColorBase_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct SDY1_specification_typ_ColorBase_ {
  /* ------------------------- inputs --------------------------- */
  SGLint32 ColorStyle;
  /* ------------------------- outputs -------------------------- */
  SGLint32 ColorBase;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} SDY1_specification_typ_ColorBase;

/* Associated functions */
extern void SDY1_specification_ColorBase_init(SDY1_specification_typ_ColorBase *pContext);
extern void SDY1_specification_ColorBase_predraw(SDY1_specification_typ_ColorBase *pContext);
extern void SDY1_specification_ColorBase_draw(SDY1_specification_typ_ColorBase *pContext, SGLint32 pPriority);
extern SDY1_specification_typ_ColorBase * SDY1_specification_ColorBase_alloc(void);
extern void SDY1_specification_ColorBase_free(SDY1_specification_typ_ColorBase *pContext);

#endif /* SDY1_SPECIFICATION_COLORBASE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-13T10:58:25
 *********************************************************/

