/*********************************************************
 **
 ** File  SDY1_specification_SliderThumb.c
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\SliderThumb.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2018-01-13T10:58:27
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY1_specification\Code -prefix SDY1_specification_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\InfiniteKnob.wgfx
 *********************************************************/

/* Inlined constants:
   Lit_color=2
   UnLit_color=1
   WL_BACK1=2
   WL_BACK2=3
   WL_BACK3=4
   WL_INNER=9
   WL_SELECT_BACK=7
   WL_SELECT_BACK2=8
   WL_WHITE=0
   inv_sqrt2=0.707
 */

#include "SDY1_specification_SliderThumb.h"
#include "SDY1_specification_imported_functions.h"
#include "sgl_simu.h"


#include <stdlib.h>
#include <string.h>

SDY1_specification_typ_SliderThumb * SDY1_specification_SliderThumb_alloc(void)
{
  SDY1_specification_typ_SliderThumb *lContext = malloc(sizeof(SDY1_specification_typ_SliderThumb));
  memset(lContext, 0L, sizeof(SDY1_specification_typ_SliderThumb));
  return lContext;
}

void SDY1_specification_SliderThumb_free(SDY1_specification_typ_SliderThumb *pContext)
{
  free(pContext);
}


void SDY1_specification_SliderThumb_init(SDY1_specification_typ_SliderThumb *pContext)
{
  SDY1_specification_SliderThumb_S_SizeX(pContext, 120.0F);
  SDY1_specification_SliderThumb_S_SizeY(pContext, 50.0F);
  SDY1_specification_SliderThumb_S_PoppingOutward(pContext, 1);
  SDY1_specification_SliderThumb_S_Enable(pContext, 1);
  SDY1_specification_SliderThumb_S_Style(pContext, 1L);
  SDY1_specification_SliderThumb_S_BaseColor(pContext, 1000L);
  SDY1_specification_SliderThumb_S_Hover(pContext, 0);
  SDY1_specification_SliderThumb_S_Inside(pContext, 0);
  SDY1_specification_SliderThumb_S_Radius(pContext, 21.0F);
  SDY1_specification_SliderThumb_S_OutlineRadius(pContext, 6.0F);

  pContext->_parentPriority = 0L;

}

void SDY1_specification_SliderThumb_predraw(SDY1_specification_typ_SliderThumb *pContext)
{
  SDY1_specification_SliderThumb_S_Inside(pContext, 0);

}

void SDY1_specification_SliderThumb_draw(SDY1_specification_typ_SliderThumb *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: SliderThumb, Type: container, OID: aa26e86b-1344-4cd9-9f8f-4fe30272caab */
    {

      /* Object: rectangle_area, Type: rectangleArea, OID: 9e06e465-f732-41d9-baf0-892d9a0384bd */
      {
        SGLfloat lX = 0.0F;
        SGLfloat lY = 0.0F;
        SDY1_specification_locate(-1L, &lX, &lY);
        SDY1_specification_SliderThumb_G_Inside(pContext) = f044(lX, lY, SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeX(pContext)), 2.0F), SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeY(pContext)), 2.0F), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F));
      }

      /* Object: Radius, Type: assignment, OID: 53069eec-c372-4c57-9394-d0929bbe6013 */
      {
        SDY1_specification_SliderThumb_G_Radius(pContext) = (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_SizeY(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F));
      }

      /* Object: OutlineRadius, Type: assignment, OID: c989b940-7ebf-4086-bc90-a71b068e6137 */
      {
        SDY1_specification_SliderThumb_G_OutlineRadius(pContext) = (SGLfloat_lt(SDY1_specification_SliderThumb_G_Radius(pContext), 7.0F) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_Radius(pContext), 1.0F) : 6.0F);
      }

      /* Object: Style, Type: conditional, OID: b3372b76-733a-4351-968c-25454b2a80f2 */
      {
        switch (SDY1_specification_SliderThumb_G_Style(pContext)) {

        case 1L:

          /* Object: RECT, Type: container, OID: 9a2395fa-e249-4bdd-adbb-71a5cce8f252 */
          {
            f073(SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeX(pContext)), 2.0F), SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeY(pContext)), 2.0F));

            /* Object: Background, Type: rectangle, OID: 5fb05b24-0337-4374-adf6-8544a7f04079 */
            {
              if (SGLint32_ge(SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L), 0L)) {
                /* color object part */
                f013(SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L));
                f009(f224);
                f008(f148);
                f036(255L);
                f009(f167);
                f009(f230);
                /* fill object part */
                f009(f227);
                f001(f109);
                f035(0.0F, 0.0F);
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), 0.0F);
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_SizeY(pContext));
                f035(0.0F, SDY1_specification_SliderThumb_G_SizeY(pContext));
                f002();
              }
            }

            /* Object: Gradient, Type: rectangle, OID: 928aac9b-ca14-41a5-aa82-92498fb52c7d */
            {
              if (SDY1_specification_SliderThumb_G_Enable(pContext)) {
                /* color object part */
                f013(1L);
                f008(f224);
                f008(f148);
                f036(255L);
                /* texture object part */
                f003(f167, 241L);
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = 0.0F;
                  lY[0UL] = 0.0F;
                  lX[1UL] = SDY1_specification_SliderThumb_G_SizeX(pContext);
                  lY[1UL] = SDY1_specification_SliderThumb_G_SizeY(pContext);
                  f052(2UL, lX, lY, 0.95F, 0.95F, f205, f208);
                }
                f008(f167);
                f009(f230);
                /* fill object part */
                f009(f227);
                f001(f109);
                f035(0.0F, 0.0F);
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), 0.0F);
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_SizeY(pContext));
                f035(0.0F, SDY1_specification_SliderThumb_G_SizeY(pContext));
                f002();
              }
            }

            /* Object: Disable, Type: rectangle, OID: 5c6991cb-2778-4585-bb7a-5b4e60e71dee */
            {
              if (SGLbool_or(SGLbool_not(SDY1_specification_SliderThumb_G_Enable(pContext)), SDY1_specification_SliderThumb_G_Inside(pContext))) {
                /* color object part */
                f013(1L);
                f009(f224);
                f008(f148);
                f036(128L);
                f009(f167);
                f009(f230);
                /* fill object part */
                f009(f227);
                f001(f109);
                f035(0.0F, 0.0F);
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), 0.0F);
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_SizeY(pContext));
                f035(0.0F, SDY1_specification_SliderThumb_G_SizeY(pContext));
                f002();
              }
            }

            /* Object: BorderTL, Type: line, OID: 68a2c425-b92e-4a56-8e3b-6d503d95579b */
            {
              if (SGLint32_ge((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 2L : 1L), 0L)) {
                /* outline object part */
                f009(f167);
                f013((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 2L : 1L));
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f216);
                f036((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 255L : 64L));
                f001(f102);
                f035(0.0F, 0.0F);
                f035(0.0F, SDY1_specification_SliderThumb_G_SizeY(pContext));
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_SizeY(pContext));
                f002();
              }
            }

            /* Object: BorderBR, Type: line, OID: e9d96798-0f60-4d88-b7e6-cc70c6a9db67 */
            {
              if (SGLint32_ge((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 1L : 2L), 0L)) {
                /* outline object part */
                f009(f167);
                f013((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 1L : 2L));
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f216);
                f036((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 64L : 255L));
                f001(f102);
                f035(0.0F, 0.0F);
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), 0.0F);
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_SizeY(pContext));
                f002();
              }
            }
            f074();
          }
          break;

        case 2L:

          /* Object: RND, Type: container, OID: 13d7f497-7f9e-40d9-b027-40b0295c8768 */
          {
            f073(SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeX(pContext)), 2.0F), SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeY(pContext)), 2.0F));

            /* Object: Background_1, Type: shape, OID: 3c069f95-7517-4806-97ce-73b08279d599 */
            {
              if (SGLint32_ge(SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L), 0L)) {
                /* color object part */
                f013(SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L));
                f009(f224);
                f009(f148);
                f036(255L);
                f009(f167);
                f009(f230);
                /* fill object part */
                f009(f227);
                f001(f109);
                f035(0.0F, SDY1_specification_SliderThumb_G_OutlineRadius(pContext));
                f035(0.0F, SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)));
                f051(1, 90.0F);
                f035(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), SDY1_specification_SliderThumb_G_SizeY(pContext));
                f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)), SDY1_specification_SliderThumb_G_SizeY(pContext));
                f051(1, 90.0F);
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)));
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext));
                f051(1, 90.0F);
                f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)), 0.0F);
                f035(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), 0.0F);
                f051(1, 90.0F);
                f002();
              }
            }

            /* Object: Gradient_1, Type: shape, OID: 492a6b6f-eaa8-423b-965c-b89f416e1936 */
            {
              if (SDY1_specification_SliderThumb_G_Enable(pContext)) {
                /* color object part */
                f013(1L);
                f008(f224);
                f009(f148);
                f036(255L);
                /* texture object part */
                f003(f167, 241L);
                {
                  SGLfloat lX[16UL];
                  SGLfloat lY[16UL];
                  lX[0UL] = 0.0F;
                  lY[0UL] = SDY1_specification_SliderThumb_G_OutlineRadius(pContext);
                  lX[1UL] = 0.0F;
                  lY[1UL] = SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext));
                  f071(1, 90.0F, 0.0F, SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)), SDY1_specification_SliderThumb_G_OutlineRadius(pContext), SDY1_specification_SliderThumb_G_SizeY(pContext), &(lX[2UL]), &(lY[2UL]), &(lX[3UL]), &(lY[3UL]));
                  lX[4UL] = SDY1_specification_SliderThumb_G_OutlineRadius(pContext);
                  lY[4UL] = SDY1_specification_SliderThumb_G_SizeY(pContext);
                  lX[5UL] = SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext));
                  lY[5UL] = SDY1_specification_SliderThumb_G_SizeY(pContext);
                  f071(1, 90.0F, SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)), SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)), &(lX[6UL]), &(lY[6UL]), &(lX[7UL]), &(lY[7UL]));
                  lX[8UL] = SDY1_specification_SliderThumb_G_SizeX(pContext);
                  lY[8UL] = SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext));
                  lX[9UL] = SDY1_specification_SliderThumb_G_SizeX(pContext);
                  lY[9UL] = SDY1_specification_SliderThumb_G_OutlineRadius(pContext);
                  f071(1, 90.0F, SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext), SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)), 0.0F, &(lX[10UL]), &(lY[10UL]), &(lX[11UL]), &(lY[11UL]));
                  lX[12UL] = SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext));
                  lY[12UL] = 0.0F;
                  lX[13UL] = SDY1_specification_SliderThumb_G_OutlineRadius(pContext);
                  lY[13UL] = 0.0F;
                  f071(1, 90.0F, SDY1_specification_SliderThumb_G_OutlineRadius(pContext), 0.0F, 0.0F, SDY1_specification_SliderThumb_G_OutlineRadius(pContext), &(lX[14UL]), &(lY[14UL]), &(lX[15UL]), &(lY[15UL]));
                  f052(16UL, lX, lY, 1.0F, 1.0F, f205, f208);
                }
                f008(f167);
                f009(f230);
                /* fill object part */
                f009(f227);
                f001(f109);
                f035(0.0F, SDY1_specification_SliderThumb_G_OutlineRadius(pContext));
                f035(0.0F, SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)));
                f051(1, 90.0F);
                f035(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), SDY1_specification_SliderThumb_G_SizeY(pContext));
                f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)), SDY1_specification_SliderThumb_G_SizeY(pContext));
                f051(1, 90.0F);
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)));
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext));
                f051(1, 90.0F);
                f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)), 0.0F);
                f035(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), 0.0F);
                f051(1, 90.0F);
                f002();
              }
            }

            /* Object: Disable_1, Type: shape, OID: 12d2c5a6-e89c-4bde-a5de-2b7ad7b84436 */
            {
              if (SGLbool_or(SGLbool_not(SDY1_specification_SliderThumb_G_Enable(pContext)), SDY1_specification_SliderThumb_G_Inside(pContext))) {
                /* color object part */
                f013(1L);
                f009(f224);
                f009(f148);
                f036(128L);
                f009(f167);
                f009(f230);
                /* fill object part */
                f009(f227);
                f001(f109);
                f035(0.0F, SDY1_specification_SliderThumb_G_OutlineRadius(pContext));
                f035(0.0F, SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)));
                f051(1, 90.0F);
                f035(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), SDY1_specification_SliderThumb_G_SizeY(pContext));
                f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)), SDY1_specification_SliderThumb_G_SizeY(pContext));
                f051(1, 90.0F);
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)));
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext));
                f051(1, 90.0F);
                f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)), 0.0F);
                f035(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), 0.0F);
                f051(1, 90.0F);
                f002();
              }
            }

            /* Object: BorderTL_1, Type: line, OID: a65f6aef-e264-417b-a518-96265433c0bd */
            {
              if (SGLint32_ge((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 2L : 1L), 0L)) {
                /* outline object part */
                f009(f167);
                f013((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 2L : 1L));
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f215);
                f036(128L);
                f001(f102);
                f035(SGLfloat_mul(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), 0.293F), SGLfloat_mul(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), 0.293F));
                f051(1, 45.0F);
                f035(0.0F, SDY1_specification_SliderThumb_G_OutlineRadius(pContext));
                f035(0.0F, SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)));
                f051(1, 90.0F);
                f035(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), SDY1_specification_SliderThumb_G_SizeY(pContext));
                f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)), SDY1_specification_SliderThumb_G_SizeY(pContext));
                f051(1, 45.0F);
                f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_mul(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), 0.293F)), SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_mul(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), 0.293F)));
                f002();
              }
            }

            /* Object: BorderBR_1, Type: line, OID: acb0cc66-afae-4677-8ce5-f684d43f83be */
            {
              if (SGLint32_ge((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 1L : 2L), 0L)) {
                /* outline object part */
                f009(f167);
                f013((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 1L : 2L));
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f215);
                f036(128L);
                f001(f102);
                f035(SGLfloat_mul(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), 0.293F), SGLfloat_mul(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), 0.293F));
                f051(0, 45.0F);
                f035(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), 0.0F);
                f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)), 0.0F);
                f051(0, 90.0F);
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext));
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_OutlineRadius(pContext)));
                f051(0, 45.0F);
                f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_mul(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), 0.293F)), SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_mul(SDY1_specification_SliderThumb_G_OutlineRadius(pContext), 0.293F)));
                f002();
              }
            }
            f074();
          }
          break;

        case 3L:

          /* Object: OVAL, Type: container, OID: 667c46d7-c975-439b-92a9-83d5a742958a */
          {
            f073(SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeX(pContext)), 2.0F), SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeY(pContext)), 2.0F));

            /* Object: conditional_group, Type: conditional, OID: afcec15c-2a04-4a9a-8c01-2b897508ab7d */
            {
              switch ((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_SizeY(pContext)) ? 1L : 2L)) {

              case 2L:

                /* Object: High, Type: container, OID: 52c9216f-7c1a-4bde-a2a6-f243f3ec869c */
                {

                  /* Object: Background_3, Type: rectangle, OID: 18c0dcae-6039-460d-a2c2-3fcf281720ca */
                  {
                    if (SGLint32_ge(SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L), 0L)) {
                      /* color object part */
                      f013(SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L));
                      f009(f224);
                      f008(f148);
                      f036(255L);
                      f009(f167);
                      f009(f230);
                      /* fill object part */
                      f009(f227);
                      f001(f109);
                      f035(0.0F, SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F));
                      f051(0, 180.0F);
                      f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F));
                      f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)));
                      f051(0, 180.0F);
                      f035(0.0F, SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)));
                      f002();
                    }
                  }

                  /* Object: Gradient_3, Type: rectangle, OID: f8eea2bc-1efe-43ee-9f44-91ac397c9560 */
                  {
                    if (SDY1_specification_SliderThumb_G_Enable(pContext)) {
                      /* color object part */
                      f013(1L);
                      f008(f224);
                      f008(f148);
                      f036(255L);
                      /* texture object part */
                      f003(f167, 241L);
                      {
                        SGLfloat lX[6UL];
                        SGLfloat lY[6UL];
                        lX[0UL] = 0.0F;
                        lY[0UL] = SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F);
                        f071(0, 180.0F, 0.0F, SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), &(lX[1UL]), &(lY[1UL]), &(lX[2UL]), &(lY[2UL]));
                        lX[3UL] = SDY1_specification_SliderThumb_G_SizeX(pContext);
                        lY[3UL] = SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F));
                        f071(0, 180.0F, SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)), 0.0F, SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)), &(lX[4UL]), &(lY[4UL]), &(lX[5UL]), &(lY[5UL]));
                        f052(6UL, lX, lY, 0.95F, 0.95F, f205, f208);
                      }
                      f008(f167);
                      f009(f230);
                      /* fill object part */
                      f009(f227);
                      f001(f109);
                      f035(0.0F, SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F));
                      f051(0, 180.0F);
                      f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F));
                      f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)));
                      f051(0, 180.0F);
                      f035(0.0F, SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)));
                      f002();
                    }
                  }

                  /* Object: Disable_3, Type: rectangle, OID: 73988dc0-e553-4a13-aad1-cbb7fc4658be */
                  {
                    if (SGLbool_not(SDY1_specification_SliderThumb_G_Enable(pContext))) {
                      /* color object part */
                      f013(1L);
                      f009(f224);
                      f008(f148);
                      f036(128L);
                      f009(f167);
                      f009(f230);
                      /* fill object part */
                      f009(f227);
                      f001(f109);
                      f035(0.0F, SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F));
                      f051(0, 180.0F);
                      f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F));
                      f035(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)));
                      f051(0, 180.0F);
                      f035(0.0F, SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)));
                      f002();
                    }
                  }
                }
                break;

              default:
              /* case 1L */

                /* Object: Large, Type: container, OID: 611c35be-7108-4638-bec2-15dedec54021 */
                {

                  /* Object: Background_2, Type: rectangle, OID: 1d7181f3-ed64-4b79-ae1d-1d2334601d01 */
                  {
                    if (SGLint32_ge(SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L), 0L)) {
                      /* color object part */
                      f013(SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L));
                      f009(f224);
                      f008(f148);
                      f036(255L);
                      f009(f167);
                      f009(f230);
                      /* fill object part */
                      f009(f227);
                      f001(f109);
                      f035(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), 0.0F);
                      f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), 0.0F);
                      f051(0, 180.0F);
                      f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), SDY1_specification_SliderThumb_G_SizeY(pContext));
                      f035(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), SDY1_specification_SliderThumb_G_SizeY(pContext));
                      f051(0, 180.0F);
                      f002();
                    }
                  }

                  /* Object: Gradient_2, Type: rectangle, OID: c8715493-a785-42af-9a22-12f4493f141a */
                  {
                    if (SDY1_specification_SliderThumb_G_Enable(pContext)) {
                      /* color object part */
                      f013(1L);
                      f008(f224);
                      f008(f148);
                      f036(255L);
                      /* texture object part */
                      f003(f167, 241L);
                      {
                        SGLfloat lX[6UL];
                        SGLfloat lY[6UL];
                        lX[0UL] = SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F);
                        lY[0UL] = 0.0F;
                        f071(0, 180.0F, SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), 0.0F, SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), SDY1_specification_SliderThumb_G_SizeY(pContext), &(lX[1UL]), &(lY[1UL]), &(lX[2UL]), &(lY[2UL]));
                        lX[3UL] = SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F));
                        lY[3UL] = SDY1_specification_SliderThumb_G_SizeY(pContext);
                        f071(0, 180.0F, SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), 0.0F, &(lX[4UL]), &(lY[4UL]), &(lX[5UL]), &(lY[5UL]));
                        f052(6UL, lX, lY, 0.95F, 0.95F, f205, f208);
                      }
                      f008(f167);
                      f009(f230);
                      /* fill object part */
                      f009(f227);
                      f001(f109);
                      f035(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), 0.0F);
                      f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), 0.0F);
                      f051(0, 180.0F);
                      f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), SDY1_specification_SliderThumb_G_SizeY(pContext));
                      f035(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), SDY1_specification_SliderThumb_G_SizeY(pContext));
                      f051(0, 180.0F);
                      f002();
                    }
                  }

                  /* Object: Disable_2, Type: rectangle, OID: 32ea7755-685f-40fe-9d8e-ab2192797097 */
                  {
                    if (SGLbool_not(SDY1_specification_SliderThumb_G_Enable(pContext))) {
                      /* color object part */
                      f013(1L);
                      f009(f224);
                      f008(f148);
                      f036(128L);
                      f009(f167);
                      f009(f230);
                      /* fill object part */
                      f009(f227);
                      f001(f109);
                      f035(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), 0.0F);
                      f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), 0.0F);
                      f051(0, 180.0F);
                      f035(SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), SDY1_specification_SliderThumb_G_SizeY(pContext));
                      f035(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), SDY1_specification_SliderThumb_G_SizeY(pContext));
                      f051(0, 180.0F);
                      f002();
                    }
                  }
                }
                break;
              }
            }

            /* Object: BorderTL_2, Type: line, OID: 15d935a8-4559-4670-9caa-3f9789ade251 */
            {
              if (SGLint32_ge((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 2L : 1L), 0L)) {
                /* outline object part */
                f009(f167);
                f013((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 2L : 1L));
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f216);
                f036(128L);
                f001(f102);
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), 0.293F) : SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), 0.293F)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), 0.293F) : SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), 0.293F)));
                f051(1, (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 45.0F : 135.0F));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 0.0F : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : SDY1_specification_SliderThumb_G_SizeY(pContext)));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 0.0F : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F))), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)) : SDY1_specification_SliderThumb_G_SizeY(pContext)));
                f051(1, (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 135.0F : 45.0F));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), 1.707F) : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), 0.293F))), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), 0.293F)) : SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), 1.707F)));
                f002();
              }
            }

            /* Object: BorderBR_2, Type: line, OID: fcf94d37-b55d-42e1-9d30-72896011fd47 */
            {
              if (SGLint32_ge((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 1L : 2L), 0L)) {
                /* outline object part */
                f009(f167);
                f013((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 1L : 2L));
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f216);
                f036(128L);
                f001(f102);
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), 0.293F) : SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), 0.293F)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), 0.293F) : SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), 0.293F)));
                f051(0, (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 135.0F : 45.0F));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SDY1_specification_SliderThumb_G_SizeX(pContext) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : 0.0F));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SDY1_specification_SliderThumb_G_SizeX(pContext) : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F))), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)) : 0.0F));
                f051(0, (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 45.0F : 135.0F));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), 1.707F) : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), 0.293F))), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), 0.293F)) : SGLfloat_mul(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), 1.707F)));
                f002();
              }
            }
            f074();
          }
          break;

        case 4L:

          /* Object: TRIANGULAR, Type: container, OID: 6d9df0b8-917c-4d90-8def-9eed7c21934a */
          {
            f073(SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeX(pContext)), 2.0F), SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeY(pContext)), 2.0F));

            /* Object: BackGround, Type: shape, OID: b546790c-1637-43fd-81d0-d36ff8f588b0 */
            {
              if (SGLint32_ge(SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L), 0L)) {
                /* color object part */
                f013(SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L));
                f009(f224);
                f008(f148);
                f036(255L);
                f009(f167);
                f009(f230);
                /* fill object part */
                f009(f227);
                f001(f109);
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 0.0F : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : SDY1_specification_SliderThumb_G_SizeY(pContext)));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 0.0F : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F))), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)) : SDY1_specification_SliderThumb_G_SizeY(pContext)));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : SDY1_specification_SliderThumb_G_SizeX(pContext)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SDY1_specification_SliderThumb_G_SizeY(pContext) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SDY1_specification_SliderThumb_G_SizeX(pContext) : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F))), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)) : 0.0F));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SDY1_specification_SliderThumb_G_SizeX(pContext) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : 0.0F));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : 0.0F), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 0.0F : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)));
                f002();
              }
            }

            /* Object: Gradient_4, Type: shape, OID: 450596ad-7080-4345-99b4-411e65d60f44 */
            {
              if (SDY1_specification_SliderThumb_G_Enable(pContext)) {
                /* color object part */
                f013(1L);
                f008(f224);
                f008(f148);
                f036(255L);
                /* texture object part */
                f003(f167, 241L);
                {
                  SGLfloat lX[6UL];
                  SGLfloat lY[6UL];
                  lX[0UL] = (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 0.0F : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F));
                  lY[0UL] = (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : SDY1_specification_SliderThumb_G_SizeY(pContext));
                  lX[1UL] = (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 0.0F : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)));
                  lY[1UL] = (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)) : SDY1_specification_SliderThumb_G_SizeY(pContext));
                  lX[2UL] = (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : SDY1_specification_SliderThumb_G_SizeX(pContext));
                  lY[2UL] = (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SDY1_specification_SliderThumb_G_SizeY(pContext) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F));
                  lX[3UL] = (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SDY1_specification_SliderThumb_G_SizeX(pContext) : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)));
                  lY[3UL] = (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)) : 0.0F);
                  lX[4UL] = (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SDY1_specification_SliderThumb_G_SizeX(pContext) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F));
                  lY[4UL] = (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : 0.0F);
                  lX[5UL] = (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : 0.0F);
                  lY[5UL] = (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 0.0F : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F));
                  f052(6UL, lX, lY, 0.95F, 0.95F, f205, f208);
                }
                f008(f167);
                f009(f230);
                /* fill object part */
                f009(f227);
                f001(f109);
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 0.0F : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : SDY1_specification_SliderThumb_G_SizeY(pContext)));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 0.0F : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F))), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)) : SDY1_specification_SliderThumb_G_SizeY(pContext)));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : SDY1_specification_SliderThumb_G_SizeX(pContext)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SDY1_specification_SliderThumb_G_SizeY(pContext) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SDY1_specification_SliderThumb_G_SizeX(pContext) : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F))), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)) : 0.0F));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SDY1_specification_SliderThumb_G_SizeX(pContext) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : 0.0F));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : 0.0F), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 0.0F : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)));
                f002();
              }
            }

            /* Object: Disable_4, Type: shape, OID: 27786a84-c932-4db8-a6f3-28cafc69d7d7 */
            {
              if (SGLbool_or(SGLbool_not(SDY1_specification_SliderThumb_G_Enable(pContext)), SDY1_specification_SliderThumb_G_Inside(pContext))) {
                /* color object part */
                f013(1L);
                f009(f224);
                f008(f148);
                f036(128L);
                f009(f167);
                f009(f230);
                /* fill object part */
                f009(f227);
                f001(f109);
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 0.0F : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : SDY1_specification_SliderThumb_G_SizeY(pContext)));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 0.0F : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F))), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)) : SDY1_specification_SliderThumb_G_SizeY(pContext)));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : SDY1_specification_SliderThumb_G_SizeX(pContext)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SDY1_specification_SliderThumb_G_SizeY(pContext) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SDY1_specification_SliderThumb_G_SizeX(pContext) : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F))), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)) : 0.0F));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SDY1_specification_SliderThumb_G_SizeX(pContext) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : 0.0F));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : 0.0F), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 0.0F : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)));
                f002();
              }
            }

            /* Object: BorderTL_3, Type: line, OID: 458bcfa8-4ae3-4203-b477-7a7a82407fb7 */
            {
              if (SGLint32_ge((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 2L : 1L), 0L)) {
                /* outline object part */
                f009(f167);
                f013((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 2L : 1L));
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f216);
                f036((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 255L : 64L));
                f001(f102);
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 4.0F) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 4.0F)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 4.0F) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 4.0F)));
                f035(0.0F, (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? 0.0F : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)) : SDY1_specification_SliderThumb_G_SizeY(pContext)));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F))), SDY1_specification_SliderThumb_G_SizeY(pContext));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 4.0F)) : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 4.0F))), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 4.0F)) : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 4.0F))));
                f002();
              }
            }

            /* Object: BorderBR_3, Type: line, OID: 084bf4f4-5315-4869-bca8-ced7ca5e3535 */
            {
              if (SGLint32_ge((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 1L : 2L), 0L)) {
                /* outline object part */
                f009(f167);
                f013((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 1L : 2L));
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f216);
                f036((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 64L : 255L));
                f001(f102);
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 4.0F) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 4.0F)), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 4.0F) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 4.0F)));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)), 0.0F);
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SDY1_specification_SliderThumb_G_SizeX(pContext) : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F))), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F) : 0.0F));
                f035(SDY1_specification_SliderThumb_G_SizeX(pContext), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F)) : SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F)));
                f035((SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 4.0F)) : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeX(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 4.0F))), (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext)) ? SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 4.0F)) : SGLfloat_sub(SDY1_specification_SliderThumb_G_SizeY(pContext), SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 4.0F))));
                f002();
              }
            }
            f074();
          }
          break;

        case 6L:

          /* Object: BALL, Type: container, OID: 3977f3c9-254c-435d-92ad-a2a4481a630d */
          {

            /* Object: circle_out, Type: circle, OID: 1b6cd9ef-a52b-4da1-b3d9-019dcc929200 */
            {
              if (SGLint32_ge((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 8L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 4L)), 0L)) {
                /* color object part */
                f013((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 8L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 4L)));
                f009(f224);
                f009(f148);
                f036(255L);
                f009(f167);
                f009(f230);
                /* fill object part */
                f030(0.0F, 0.0F, SDY1_specification_SliderThumb_G_Radius(pContext), 0.0F, 360.0F, 1, f170);
                /* outline object part */
                f009(f167);
                f013((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 8L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 4L)));
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f216);
                f036(255L);
                f030(0.0F, 0.0F, SDY1_specification_SliderThumb_G_Radius(pContext), 0.0F, 360.0F, 1, f172);
              }
            }

            /* Object: circle_in, Type: circle, OID: 84b73f9b-aed0-42b8-9171-bf5a8716efa4 */
            {
              if (SGLbool_or(SGLint32_ge((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)), 0L), SGLint32_ge((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 253L : 245L), 0L))) {
                if (SGLint32_ge((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)), 0L)) {
                  /* color object part */
                  f013((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)));
                  f008(f224);
                  f009(f148);
                  f036(255L);
                }
                else {
                  f009(f224);
                }
                if (SGLint32_ge((SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 253L : 245L), 0L)) {
                  /* texture object part */
                  f003(f167, (SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? 253L : 245L));
                  {
                    SGLfloat lX[2UL];
                    SGLfloat lY[2UL];
                    lX[0UL] = SGLfloat_neg(SDY1_specification_SliderThumb_G_Radius(pContext));
                    lY[0UL] = SGLfloat_neg(SDY1_specification_SliderThumb_G_Radius(pContext));
                    lX[1UL] = SDY1_specification_SliderThumb_G_Radius(pContext);
                    lY[1UL] = SDY1_specification_SliderThumb_G_Radius(pContext);
                    f052(2UL, lX, lY, 1.0F, 1.0F, f205, f208);
                  }
                  f008(f167);
                }
                else {
                  f009(f167);
                }
                f009(f230);
                /* fill object part */
                f030(0.0F, 0.0F, SDY1_specification_SliderThumb_G_Radius(pContext), 0.0F, 360.0F, 1, f170);
              }
              if (SGLint32_ge((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 8L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 4L)), 0L)) {
                /* outline object part */
                f009(f167);
                f013((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 8L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 4L)));
                f085(-1L);
                f015(0L);
                f014(0L);
                f009(f150);
                f068(f216);
                f036(255L);
                f030(0.0F, 0.0F, SDY1_specification_SliderThumb_G_Radius(pContext), 0.0F, 360.0F, 1, f172);
              }
            }

            /* Object: group, Type: container, OID: e797d608-075a-4af9-a82b-7e158218baf3 */
            {
              if (SDY1_specification_SliderThumb_G_PoppingOutward(pContext)) {

                /* Object: ellipse, Type: ellipse, OID: 72f3528b-fcda-47af-9cf1-b6f99258f942 */
                {
                  /* color object part */
                  f013(1007L);
                  f009(f224);
                  f009(f148);
                  f036(128L);
                  f009(f167);
                  f009(f230);
                  /* fill object part */
                  f072(0.0F, SGLfloat_mul(SDY1_specification_SliderThumb_G_Radius(pContext), 0.6F), SGLfloat_mul(SDY1_specification_SliderThumb_G_Radius(pContext), 0.4F), SGLfloat_mul(SDY1_specification_SliderThumb_G_Radius(pContext), 0.25F), 0.0F, 360.0F, 1, f219);
                  if (SGLint32_ge((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)), 0L)) {
                    /* outline object part */
                    f013((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)));
                    f085(-1L);
                    f015(0L);
                    f014(0L);
                    f009(f150);
                    f068(f216);
                    f072(0.0F, SGLfloat_mul(SDY1_specification_SliderThumb_G_Radius(pContext), 0.6F), SGLfloat_mul(SDY1_specification_SliderThumb_G_Radius(pContext), 0.4F), SGLfloat_mul(SDY1_specification_SliderThumb_G_Radius(pContext), 0.25F), 0.0F, 360.0F, 1, f220);
                  }
                }

                /* Object: ellipse_1, Type: ellipse, OID: b71d4fb1-5957-4c2b-a2fc-5af4444616db */
                {
                  if (SGLint32_ge((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)), 0L)) {
                    /* color object part */
                    f013((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)));
                    f036(255L);
                    /* fill object part */
                    f072(0.0F, SGLfloat_mul(SDY1_specification_SliderThumb_G_Radius(pContext), 0.6F), SGLfloat_mul(SDY1_specification_SliderThumb_G_Radius(pContext), 0.4F), SGLfloat_mul(SDY1_specification_SliderThumb_G_Radius(pContext), 0.25F), 0.0F, 360.0F, 1, f219);
                    /* outline object part */
                    f013((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)));
                    f085(-1L);
                    f015(0L);
                    f014(0L);
                    f009(f150);
                    f068(f216);
                    f036(255L);
                    f072(0.0F, SGLfloat_mul(SDY1_specification_SliderThumb_G_Radius(pContext), 0.6F), SGLfloat_mul(SDY1_specification_SliderThumb_G_Radius(pContext), 0.4F), SGLfloat_mul(SDY1_specification_SliderThumb_G_Radius(pContext), 0.25F), 0.0F, 360.0F, 1, f220);
                  }
                }
              }
            }
          }
          break;

        default:
        /* case 5L */

          /* Object: NEEDLE, Type: container, OID: 1bd27f32-4219-452c-898d-e475162e9ca2 */
          {

            /* Object: Tall, Type: container, OID: 640bb882-4ae4-4a25-8800-1877a17d9f0f */
            {
              if (SGLfloat_gt(SDY1_specification_SliderThumb_G_SizeY(pContext), SDY1_specification_SliderThumb_G_SizeX(pContext))) {

                /* Object: shape, Type: shape, OID: 9c8dce0c-39e0-4b1a-8a06-ae976de5cb8f */
                {
                  if (SGLint32_ge((SDY1_specification_SliderThumb_G_Enable(pContext) ? (SDY1_specification_SliderThumb_G_Hover(pContext) ? SDY1_specification_SliderThumb_G_BaseColor(pContext) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 2L)) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)), 0L)) {
                    /* color object part */
                    f013((SDY1_specification_SliderThumb_G_Enable(pContext) ? (SDY1_specification_SliderThumb_G_Hover(pContext) ? SDY1_specification_SliderThumb_G_BaseColor(pContext) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 2L)) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)));
                    f009(f224);
                    f008(f148);
                    f036(255L);
                    f009(f167);
                    f009(f230);
                    /* fill object part */
                    f009(f227);
                    f001(f109);
                    f035(0.0F, SGLfloat_add(SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeY(pContext)), 2.0F), 0.5F));
                    f035(SGLfloat_add(SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeX(pContext)), 2.0F), 0.5F), 0.0F);
                    f051(1, 220.0F);
                    f035(SGLfloat_sub(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), 1.0F), 0.0F);
                    f002();
                  }
                }

                /* Object: shape_1, Type: shape, OID: f8b82494-d01e-4de4-aa17-57098b3243f9 */
                {
                  if (SGLint32_ge((SDY1_specification_SliderThumb_G_Enable(pContext) ? (SDY1_specification_SliderThumb_G_Hover(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 2L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 4L)), 0L)) {
                    /* color object part */
                    f013((SDY1_specification_SliderThumb_G_Enable(pContext) ? (SDY1_specification_SliderThumb_G_Hover(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 2L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 4L)));
                    f008(f224);
                    f008(f148);
                    f036(255L);
                  }
                  else {
                    f009(f224);
                  }
                  /* texture object part */
                  f003(f167, 247L);
                  {
                    SGLfloat lX[5UL];
                    SGLfloat lY[5UL];
                    lX[0UL] = 0.0F;
                    lY[0UL] = SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeY(pContext)), 2.0F);
                    lX[1UL] = SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeX(pContext)), 2.0F);
                    lY[1UL] = 0.0F;
                    f071(1, 220.0F, SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeX(pContext)), 2.0F), 0.0F, SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), 0.0F, &(lX[2UL]), &(lY[2UL]), &(lX[3UL]), &(lY[3UL]));
                    lX[4UL] = SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F);
                    lY[4UL] = 0.0F;
                    f052(5UL, lX, lY, 0.95F, 0.95F, f205, f208);
                  }
                  f008(f167);
                  f009(f230);
                  /* fill object part */
                  f009(f227);
                  f001(f109);
                  f035(0.0F, SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeY(pContext)), 2.0F));
                  f035(SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeX(pContext)), 2.0F), 0.0F);
                  f051(1, 220.0F);
                  f035(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), 0.0F);
                  f002();
                }

                /* Object: circle, Type: circle, OID: f6f1fa93-acbc-4a36-acba-b80ebef4a884 */
                {
                  if (SGLint32_ge((SDY1_specification_SliderThumb_G_Enable(pContext) ? (SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 8L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L)) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 4L)), 0L)) {
                    /* color object part */
                    f013((SDY1_specification_SliderThumb_G_Enable(pContext) ? (SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 8L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L)) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 4L)));
                    f009(f224);
                    f009(f148);
                    f036(255L);
                    f009(f167);
                    /* fill object part */
                    f030(0.0F, SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 5.0F), SGLfloat_mul(SDY1_specification_SliderThumb_G_SizeX(pContext), 0.34F), 0.0F, 360.0F, 1, f170);
                  }
                  if (SGLint32_ge((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 9L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 2L)), 0L)) {
                    /* outline object part */
                    f009(f167);
                    f013((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 9L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 2L)));
                    f085(-1L);
                    f015(1L);
                    f014(0L);
                    f009(f150);
                    f068(f216);
                    f036(255L);
                    f030(0.0F, SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 5.0F), SGLfloat_mul(SDY1_specification_SliderThumb_G_SizeX(pContext), 0.34F), 0.0F, 360.0F, 1, f172);
                  }
                }
              }
            }

            /* Object: Wide, Type: container, OID: 39a908f5-cdb2-407b-96fa-724dde404cba */
            {
              if (SGLfloat_ge(SDY1_specification_SliderThumb_G_SizeX(pContext), SDY1_specification_SliderThumb_G_SizeY(pContext))) {

                /* Object: shape_2, Type: shape, OID: 2afc0657-62e5-42d9-88d0-18cbfeef393a */
                {
                  if (SGLint32_ge((SDY1_specification_SliderThumb_G_Enable(pContext) ? (SDY1_specification_SliderThumb_G_Hover(pContext) ? SDY1_specification_SliderThumb_G_BaseColor(pContext) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 2L)) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)), 0L)) {
                    /* color object part */
                    f013((SDY1_specification_SliderThumb_G_Enable(pContext) ? (SDY1_specification_SliderThumb_G_Hover(pContext) ? SDY1_specification_SliderThumb_G_BaseColor(pContext) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 2L)) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)));
                    f009(f224);
                    f008(f148);
                    f036(255L);
                    f009(f167);
                    f009(f230);
                    /* fill object part */
                    f009(f227);
                    f001(f109);
                    f035(SGLfloat_sub(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), 1.0F), 0.0F);
                    f035(0.0F, SGLfloat_add(SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeY(pContext)), 2.0F), 0.5F));
                    f051(1, 220.0F);
                    f035(0.0F, SGLfloat_sub(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), 0.5F));
                    f002();
                  }
                }

                /* Object: shape_3, Type: shape, OID: ce89eb25-9a5b-43dc-a464-41ff150f5ea9 */
                {
                  if (SGLint32_ge((SDY1_specification_SliderThumb_G_Enable(pContext) ? (SDY1_specification_SliderThumb_G_Hover(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 2L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 4L)), 0L)) {
                    /* color object part */
                    f013((SDY1_specification_SliderThumb_G_Enable(pContext) ? (SDY1_specification_SliderThumb_G_Hover(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 2L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 3L)) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 4L)));
                    f008(f224);
                    f008(f148);
                    f036(255L);
                  }
                  else {
                    f009(f224);
                  }
                  /* texture object part */
                  f003(f167, 245L);
                  {
                    SGLfloat lX[5UL];
                    SGLfloat lY[5UL];
                    lX[0UL] = SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F);
                    lY[0UL] = 0.0F;
                    lX[1UL] = 0.0F;
                    lY[1UL] = SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeY(pContext)), 2.0F);
                    f071(1, 220.0F, 0.0F, SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeY(pContext)), 2.0F), 0.0F, SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F), &(lX[2UL]), &(lY[2UL]), &(lX[3UL]), &(lY[3UL]));
                    lX[4UL] = 0.0F;
                    lY[4UL] = SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F);
                    f052(5UL, lX, lY, 0.95F, 0.95F, f205, f208);
                  }
                  f008(f167);
                  f009(f230);
                  /* fill object part */
                  f009(f227);
                  f001(f109);
                  f035(SGLfloat_div(SDY1_specification_SliderThumb_G_SizeX(pContext), 2.0F), 0.0F);
                  f035(0.0F, SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeY(pContext)), 2.0F));
                  f051(1, 220.0F);
                  f035(0.0F, SGLfloat_div(SDY1_specification_SliderThumb_G_SizeY(pContext), 2.0F));
                  f002();
                }

                /* Object: circle_1, Type: circle, OID: 49ceb4ce-288c-4687-911f-0492c84ff2e9 */
                {
                  if (SGLint32_ge((SDY1_specification_SliderThumb_G_Enable(pContext) ? (SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 8L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L)) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 4L)), 0L)) {
                    /* color object part */
                    f013((SDY1_specification_SliderThumb_G_Enable(pContext) ? (SDY1_specification_SliderThumb_G_PoppingOutward(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 8L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 7L)) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 4L)));
                    f009(f224);
                    f009(f148);
                    f036(255L);
                    f009(f167);
                    /* fill object part */
                    f030(SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeY(pContext)), 5.0F), 0.0F, SGLfloat_mul(SDY1_specification_SliderThumb_G_SizeY(pContext), 0.34F), 0.0F, 360.0F, 1, f170);
                  }
                  if (SGLint32_ge((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 9L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 2L)), 0L)) {
                    /* outline object part */
                    f009(f167);
                    f013((SDY1_specification_SliderThumb_G_Enable(pContext) ? SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 9L) : SGLint32_add(SDY1_specification_SliderThumb_G_BaseColor(pContext), 2L)));
                    f085(-1L);
                    f015(1L);
                    f014(0L);
                    f009(f150);
                    f068(f216);
                    f036(255L);
                    f030(SGLfloat_div(SGLfloat_neg(SDY1_specification_SliderThumb_G_SizeY(pContext)), 5.0F), 0.0F, SGLfloat_mul(SDY1_specification_SliderThumb_G_SizeY(pContext), 0.34F), 0.0F, 360.0F, 1, f172);
                  }
                }
              }
            }
          }
          break;
        }
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2018-01-13T10:58:27
 *********************************************************/

