/*********************************************************
 **
 ** File  SDY1_specification_SliderThumb.h
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\SliderThumb.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2018-01-13T10:58:27
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY1_specification\Code -prefix SDY1_specification_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\InfiniteKnob.wgfx
 *********************************************************/

/* Inlined constants:
   Lit_color=2
   UnLit_color=1
   WL_BACK1=2
   WL_BACK2=3
   WL_BACK3=4
   WL_INNER=9
   WL_SELECT_BACK=7
   WL_SELECT_BACK2=8
   WL_WHITE=0
   inv_sqrt2=0.707
 */

#ifndef SDY1_SPECIFICATION_SLIDERTHUMB_H
#define SDY1_SPECIFICATION_SLIDERTHUMB_H

#include "sgl_types.h"


/* Accessors */
#define SDY1_specification_SliderThumb_G_SizeX(_C_) (_C_)->SizeX
#define SDY1_specification_SliderThumb_S_SizeX(_C_,_V_) (_C_)->SizeX = (_V_)
#define SDY1_specification_SliderThumb_G_SizeY(_C_) (_C_)->SizeY
#define SDY1_specification_SliderThumb_S_SizeY(_C_,_V_) (_C_)->SizeY = (_V_)
#define SDY1_specification_SliderThumb_G_PoppingOutward(_C_) (_C_)->PoppingOutward
#define SDY1_specification_SliderThumb_S_PoppingOutward(_C_,_V_) (_C_)->PoppingOutward = (_V_)
#define SDY1_specification_SliderThumb_G_Enable(_C_) (_C_)->Enable
#define SDY1_specification_SliderThumb_S_Enable(_C_,_V_) (_C_)->Enable = (_V_)
#define SDY1_specification_SliderThumb_G_Style(_C_) (_C_)->Style
#define SDY1_specification_SliderThumb_S_Style(_C_,_V_) (_C_)->Style = (_V_)
#define SDY1_specification_SliderThumb_G_BaseColor(_C_) (_C_)->BaseColor
#define SDY1_specification_SliderThumb_S_BaseColor(_C_,_V_) (_C_)->BaseColor = (_V_)
#define SDY1_specification_SliderThumb_G_Hover(_C_) (_C_)->Hover
#define SDY1_specification_SliderThumb_S_Hover(_C_,_V_) (_C_)->Hover = (_V_)
#define SDY1_specification_SliderThumb_G_Inside(_C_) (_C_)->Inside
#define SDY1_specification_SliderThumb_S_Inside(_C_,_V_) (_C_)->Inside = (_V_)
#define SDY1_specification_SliderThumb_G_Radius(_C_) (_C_)->Radius
#define SDY1_specification_SliderThumb_S_Radius(_C_,_V_) (_C_)->Radius = (_V_)
#define SDY1_specification_SliderThumb_G_OutlineRadius(_C_) (_C_)->OutlineRadius
#define SDY1_specification_SliderThumb_S_OutlineRadius(_C_,_V_) (_C_)->OutlineRadius = (_V_)
#define SDY1_specification_SliderThumb_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct SDY1_specification_typ_SliderThumb_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat SizeX;
  SGLfloat SizeY;
  SGLbool PoppingOutward;
  SGLbool Enable;
  SGLint32 Style;
  SGLint32 BaseColor;
  SGLbool Hover;
  /* ------------------------- outputs -------------------------- */
  SGLbool Inside;
  SGLfloat Radius;
  /* ------------------------- locals --------------------------- */
  SGLfloat OutlineRadius;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} SDY1_specification_typ_SliderThumb;

/* Associated functions */
extern void SDY1_specification_SliderThumb_init(SDY1_specification_typ_SliderThumb *pContext);
extern void SDY1_specification_SliderThumb_predraw(SDY1_specification_typ_SliderThumb *pContext);
extern void SDY1_specification_SliderThumb_draw(SDY1_specification_typ_SliderThumb *pContext, SGLint32 pPriority);
extern SDY1_specification_typ_SliderThumb * SDY1_specification_SliderThumb_alloc(void);
extern void SDY1_specification_SliderThumb_free(SDY1_specification_typ_SliderThumb *pContext);

#endif /* SDY1_SPECIFICATION_SLIDERTHUMB_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-13T10:58:27
 *********************************************************/

