/*********************************************************
 **
 ** File  SDY1_specification_GaugeVertical.h
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\GaugeVertical.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2018-01-13T10:58:27
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY1_specification\Code -prefix SDY1_specification_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\InfiniteKnob.wgfx
 *********************************************************/

/* Inlined constants:
   GRAD_SIZE=10.0
   INNER_THICKNESS=1.0
   OUTER_THICKNESS=2.0
   OUTLINE_RADIUS=8.0
   WL_BACK1=2
   WL_BACK3=4
   WL_GRADUATION_OUT=16
   WL_LEGEND=15
   WL_SELECT_BACK=7
   WL_SELECT_BACK2=8
   WL_WHITE=0
 */

#ifndef SDY1_SPECIFICATION_GAUGEVERTICAL_H
#define SDY1_SPECIFICATION_GAUGEVERTICAL_H

#include "sgl_types.h"
#include "kcg_assign.h"

#include "SDY1_specification_FrameShape.h"
#include "SDY1_specification_Scale.h"
#include "SDY1_specification_Graduation_element.h"

/* Accessors */
#define SDY1_specification_GaugeVertical_G_SizeX(_C_) (_C_)->SizeX
#define SDY1_specification_GaugeVertical_S_SizeX(_C_,_V_) (_C_)->SizeX = (_V_)
#define SDY1_specification_GaugeVertical_G_SizeY(_C_) (_C_)->SizeY
#define SDY1_specification_GaugeVertical_S_SizeY(_C_,_V_) (_C_)->SizeY = (_V_)
#define SDY1_specification_GaugeVertical_G_Value(_C_) (_C_)->Value
#define SDY1_specification_GaugeVertical_S_Value(_C_,_V_) (_C_)->Value = (_V_)
#define SDY1_specification_GaugeVertical_G_MaxValue(_C_) (_C_)->MaxValue
#define SDY1_specification_GaugeVertical_S_MaxValue(_C_,_V_) (_C_)->MaxValue = (_V_)
#define SDY1_specification_GaugeVertical_G_MinValue(_C_) (_C_)->MinValue
#define SDY1_specification_GaugeVertical_S_MinValue(_C_,_V_) (_C_)->MinValue = (_V_)
#define SDY1_specification_GaugeVertical_G_Style(_C_) (_C_)->Style
#define SDY1_specification_GaugeVertical_S_Style(_C_,_V_) (_C_)->Style = (_V_)
#define SDY1_specification_GaugeVertical_G_BaseColor(_C_) (_C_)->BaseColor
#define SDY1_specification_GaugeVertical_S_BaseColor(_C_,_V_) (_C_)->BaseColor = (_V_)
#define SDY1_specification_GaugeVertical_G_BackColor(_C_) (_C_)->BackColor
#define SDY1_specification_GaugeVertical_S_BackColor(_C_,_V_) (_C_)->BackColor = (_V_)
#define SDY1_specification_GaugeVertical_G_FrontColor(_C_) (_C_)->FrontColor
#define SDY1_specification_GaugeVertical_S_FrontColor(_C_,_V_) (_C_)->FrontColor = (_V_)
#define SDY1_specification_GaugeVertical_G_FontColor(_C_) (_C_)->FontColor
#define SDY1_specification_GaugeVertical_S_FontColor(_C_,_V_) (_C_)->FontColor = (_V_)
#define SDY1_specification_GaugeVertical_G_Font(_C_) (_C_)->Font
#define SDY1_specification_GaugeVertical_S_Font(_C_,_V_) (_C_)->Font = (_V_)
#define SDY1_specification_GaugeVertical_G_DisplayGraduation(_C_) (_C_)->DisplayGraduation
#define SDY1_specification_GaugeVertical_S_DisplayGraduation(_C_,_V_) (_C_)->DisplayGraduation = (_V_)
#define SDY1_specification_GaugeVertical_G_DisplayValueAsDigits(_C_) (_C_)->DisplayValueAsDigits
#define SDY1_specification_GaugeVertical_S_DisplayValueAsDigits(_C_,_V_) (_C_)->DisplayValueAsDigits = (_V_)
#define SDY1_specification_GaugeVertical_G_Mirror(_C_) (_C_)->Mirror
#define SDY1_specification_GaugeVertical_S_Mirror(_C_,_V_) (_C_)->Mirror = (_V_)
#define SDY1_specification_GaugeVertical_G_Label(_C_) (*(_C_)->Label)
#define SDY1_specification_GaugeVertical_S_Label(_C_,_V_) (_C_)->Label = &(_V_)
#define SDY1_specification_GaugeVertical_G_Integral(_C_) (_C_)->Integral
#define SDY1_specification_GaugeVertical_S_Integral(_C_,_V_) (_C_)->Integral = (_V_)
#define SDY1_specification_GaugeVertical_G_Fractional(_C_) (_C_)->Fractional
#define SDY1_specification_GaugeVertical_S_Fractional(_C_,_V_) (_C_)->Fractional = (_V_)
#define SDY1_specification_GaugeVertical_G_Margin(_C_) (_C_)->Margin
#define SDY1_specification_GaugeVertical_S_Margin(_C_,_V_) (_C_)->Margin = (_V_)
#define SDY1_specification_GaugeVertical_G_FontSizeX(_C_) (_C_)->FontSizeX
#define SDY1_specification_GaugeVertical_S_FontSizeX(_C_,_V_) (_C_)->FontSizeX = (_V_)
#define SDY1_specification_GaugeVertical_G_FontSizeY(_C_) (_C_)->FontSizeY
#define SDY1_specification_GaugeVertical_S_FontSizeY(_C_,_V_) (_C_)->FontSizeY = (_V_)
#define SDY1_specification_GaugeVertical_G_OriginPx(_C_) (_C_)->OriginPx
#define SDY1_specification_GaugeVertical_S_OriginPx(_C_,_V_) kcg_assign((_C_)->OriginPx, (_V_), sizeof(SGLfloat [60UL]))
#define SDY1_specification_GaugeVertical_G_unused1(_C_) (_C_)->unused1
#define SDY1_specification_GaugeVertical_S_unused1(_C_,_V_) kcg_assign((_C_)->unused1, (_V_), sizeof(SGLfloat [120UL]))
#define SDY1_specification_GaugeVertical_G_ValueNb(_C_) (_C_)->ValueNb
#define SDY1_specification_GaugeVertical_S_ValueNb(_C_,_V_) kcg_assign((_C_)->ValueNb, (_V_), sizeof(SGLfloat [60UL]))
#define SDY1_specification_GaugeVertical_G_ElemVisible(_C_) (_C_)->ElemVisible
#define SDY1_specification_GaugeVertical_S_ElemVisible(_C_,_V_) kcg_assign((_C_)->ElemVisible, (_V_), sizeof(SGLbool [60UL]))
#define SDY1_specification_GaugeVertical_G_unused2(_C_) (_C_)->unused2
#define SDY1_specification_GaugeVertical_S_unused2(_C_,_V_) kcg_assign((_C_)->unused2, (_V_), sizeof(SGLbool [120UL]))
#define SDY1_specification_GaugeVertical_G_RunTimeMode(_C_) (_C_)->RunTimeMode
#define SDY1_specification_GaugeVertical_S_RunTimeMode(_C_,_V_) (_C_)->RunTimeMode = (_V_)
#define SDY1_specification_GaugeVertical_G_LocGraduationColor(_C_) (_C_)->LocGraduationColor
#define SDY1_specification_GaugeVertical_S_LocGraduationColor(_C_,_V_) (_C_)->LocGraduationColor = (_V_)
#define SDY1_specification_GaugeVertical_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct SDY1_specification_typ_GaugeVertical_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat SizeX;
  SGLfloat SizeY;
  SGLfloat Value;
  SGLfloat MaxValue;
  SGLfloat MinValue;
  SGLint32 Style;
  SGLint32 BaseColor;
  SGLint32 BackColor;
  SGLint32 FrontColor;
  SGLint32 FontColor;
  SGLint32 Font;
  SGLint32 DisplayGraduation;
  SGLbool DisplayValueAsDigits;
  SGLbool Mirror;
  SGLuint8 (*Label)[255UL];
  /* ------------------------- locals --------------------------- */
  SGLint32 Integral;
  SGLint32 Fractional;
  SGLfloat Margin;
  SGLfloat FontSizeX;
  SGLfloat FontSizeY;
  SGLfloat OriginPx[60UL];
  SGLfloat unused1[120UL];
  SGLfloat ValueNb[60UL];
  SGLbool ElemVisible[60UL];
  SGLbool unused2[120UL];
  SGLbool RunTimeMode;
  SGLint32 LocGraduationColor;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
  /* ------------------------- subcontexts ---------------------- */
  SDY1_specification_typ_Scale _Scale__;
  SDY1_specification_typ_Graduation_element _minmax__0;
  SDY1_specification_typ_Graduation_element _minmax__1;
} SDY1_specification_typ_GaugeVertical;

/* Associated functions */
extern void SDY1_specification_GaugeVertical_init(SDY1_specification_typ_GaugeVertical *pContext);
extern void SDY1_specification_GaugeVertical_predraw(SDY1_specification_typ_GaugeVertical *pContext);
extern void SDY1_specification_GaugeVertical_draw(SDY1_specification_typ_GaugeVertical *pContext, SGLint32 pPriority);
extern SDY1_specification_typ_GaugeVertical * SDY1_specification_GaugeVertical_alloc(void);
extern void SDY1_specification_GaugeVertical_free(SDY1_specification_typ_GaugeVertical *pContext);

#endif /* SDY1_SPECIFICATION_GAUGEVERTICAL_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-13T10:58:27
 *********************************************************/

