/*********************************************************
 **
 ** File  SDY1_specification_Highlight.h
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Highlight.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2018-01-13T10:58:27
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY1_specification\Code -prefix SDY1_specification_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\InfiniteKnob.wgfx
 *********************************************************/

/* Inlined constants:
   HaloRadius=8.0
   HighlightColor=2
 */

#ifndef SDY1_SPECIFICATION_HIGHLIGHT_H
#define SDY1_SPECIFICATION_HIGHLIGHT_H

#include "sgl_types.h"


/* Accessors */
#define SDY1_specification_Highlight_G_SizeX(_C_) (_C_)->SizeX
#define SDY1_specification_Highlight_S_SizeX(_C_,_V_) (_C_)->SizeX = (_V_)
#define SDY1_specification_Highlight_G_SizeY(_C_) (_C_)->SizeY
#define SDY1_specification_Highlight_S_SizeY(_C_,_V_) (_C_)->SizeY = (_V_)
#define SDY1_specification_Highlight_G_Highlight(_C_) (_C_)->Highlight
#define SDY1_specification_Highlight_S_Highlight(_C_,_V_) (_C_)->Highlight = (_V_)
#define SDY1_specification_Highlight_G_Style(_C_) (_C_)->Style
#define SDY1_specification_Highlight_S_Style(_C_,_V_) (_C_)->Style = (_V_)
#define SDY1_specification_Highlight_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct SDY1_specification_typ_Highlight_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat SizeX;
  SGLfloat SizeY;
  SGLbool Highlight;
  SGLint32 Style;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} SDY1_specification_typ_Highlight;

/* Associated functions */
extern void SDY1_specification_Highlight_init(SDY1_specification_typ_Highlight *pContext);
extern void SDY1_specification_Highlight_predraw(SDY1_specification_typ_Highlight *pContext);
extern void SDY1_specification_Highlight_draw(SDY1_specification_typ_Highlight *pContext, SGLint32 pPriority);
extern SDY1_specification_typ_Highlight * SDY1_specification_Highlight_alloc(void);
extern void SDY1_specification_Highlight_free(SDY1_specification_typ_Highlight *pContext);

#endif /* SDY1_SPECIFICATION_HIGHLIGHT_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-13T10:58:27
 *********************************************************/

