/*********************************************************
 **
 ** File  SDY1_specification_Graduation_element.h
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Graduation_element.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2018-01-13T10:58:26
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY1_specification\Code -prefix SDY1_specification_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\InfiniteKnob.wgfx
 *********************************************************/

#ifndef SDY1_SPECIFICATION_GRADUATION_ELEMENT_H
#define SDY1_SPECIFICATION_GRADUATION_ELEMENT_H

#include "sgl_types.h"


/* Accessors */
#define SDY1_specification_Graduation_element_G_Size(_C_) (_C_)->Size
#define SDY1_specification_Graduation_element_S_Size(_C_,_V_) (_C_)->Size = (_V_)
#define SDY1_specification_Graduation_element_G_Value(_C_) (_C_)->Value
#define SDY1_specification_Graduation_element_S_Value(_C_,_V_) (_C_)->Value = (_V_)
#define SDY1_specification_Graduation_element_G_Angle(_C_) (_C_)->Angle
#define SDY1_specification_Graduation_element_S_Angle(_C_,_V_) (_C_)->Angle = (_V_)
#define SDY1_specification_Graduation_element_G_Fractional(_C_) (_C_)->Fractional
#define SDY1_specification_Graduation_element_S_Fractional(_C_,_V_) (_C_)->Fractional = (_V_)
#define SDY1_specification_Graduation_element_G_Integral(_C_) (_C_)->Integral
#define SDY1_specification_Graduation_element_S_Integral(_C_,_V_) (_C_)->Integral = (_V_)
#define SDY1_specification_Graduation_element_G_OriginOffset(_C_) (_C_)->OriginOffset
#define SDY1_specification_Graduation_element_S_OriginOffset(_C_,_V_) (_C_)->OriginOffset = (_V_)
#define SDY1_specification_Graduation_element_G_FontColor(_C_) (_C_)->FontColor
#define SDY1_specification_Graduation_element_S_FontColor(_C_,_V_) (_C_)->FontColor = (_V_)
#define SDY1_specification_Graduation_element_G_Font(_C_) (_C_)->Font
#define SDY1_specification_Graduation_element_S_Font(_C_,_V_) (_C_)->Font = (_V_)
#define SDY1_specification_Graduation_element_G_Angle_mod(_C_) (_C_)->Angle_mod
#define SDY1_specification_Graduation_element_S_Angle_mod(_C_,_V_) (_C_)->Angle_mod = (_V_)
#define SDY1_specification_Graduation_element_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct SDY1_specification_typ_Graduation_element_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat Size;
  SGLfloat Value;
  SGLfloat Angle;
  SGLint32 Fractional;
  SGLint32 Integral;
  SGLfloat OriginOffset;
  SGLint32 FontColor;
  SGLint32 Font;
  /* ------------------------- locals --------------------------- */
  SGLfloat Angle_mod;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} SDY1_specification_typ_Graduation_element;

/* Associated functions */
extern void SDY1_specification_Graduation_element_init(SDY1_specification_typ_Graduation_element *pContext);
extern void SDY1_specification_Graduation_element_predraw(SDY1_specification_typ_Graduation_element *pContext);
extern void SDY1_specification_Graduation_element_draw(SDY1_specification_typ_Graduation_element *pContext, SGLint32 pPriority);
extern SDY1_specification_typ_Graduation_element * SDY1_specification_Graduation_element_alloc(void);
extern void SDY1_specification_Graduation_element_free(SDY1_specification_typ_Graduation_element *pContext);

#endif /* SDY1_SPECIFICATION_GRADUATION_ELEMENT_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-13T10:58:26
 *********************************************************/

