/*********************************************************
 **
 ** File  SDY1_specification_Graduation_element.c
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Graduation_element.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2018-01-13T10:58:27
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY1_specification\Code -prefix SDY1_specification_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\InfiniteKnob.wgfx
 *********************************************************/

#include "SDY1_specification_Graduation_element.h"
#include "SDY1_specification_imported_functions.h"
#include "sgl_simu.h"


#include <stdlib.h>
#include <string.h>

SDY1_specification_typ_Graduation_element * SDY1_specification_Graduation_element_alloc(void)
{
  SDY1_specification_typ_Graduation_element *lContext = malloc(sizeof(SDY1_specification_typ_Graduation_element));
  memset(lContext, 0L, sizeof(SDY1_specification_typ_Graduation_element));
  return lContext;
}

void SDY1_specification_Graduation_element_free(SDY1_specification_typ_Graduation_element *pContext)
{
  free(pContext);
}


void SDY1_specification_Graduation_element_init(SDY1_specification_typ_Graduation_element *pContext)
{
  SDY1_specification_Graduation_element_S_Size(pContext, 50.0F);
  SDY1_specification_Graduation_element_S_Value(pContext, 10.0F);
  SDY1_specification_Graduation_element_S_Angle(pContext, 0.0F);
  SDY1_specification_Graduation_element_S_Fractional(pContext, 1L);
  SDY1_specification_Graduation_element_S_Integral(pContext, 3L);
  SDY1_specification_Graduation_element_S_OriginOffset(pContext, 10.0F);
  SDY1_specification_Graduation_element_S_FontColor(pContext, 2L);
  SDY1_specification_Graduation_element_S_Font(pContext, 1L);
  SDY1_specification_Graduation_element_S_Angle_mod(pContext, 0.0F);

  pContext->_parentPriority = 0L;

}

void SDY1_specification_Graduation_element_predraw(SDY1_specification_typ_Graduation_element *pContext)
{

}

void SDY1_specification_Graduation_element_draw(SDY1_specification_typ_Graduation_element *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: Graduation, Type: container, OID: 3b5e4e3f-335c-4092-a7eb-0d2a8d9857ac */
    {
      f019();
      f022(SDY1_specification_Graduation_element_G_Angle(pContext));

      /* Object: assignment, Type: assignment, OID: 2519bcff-7713-4956-810b-eaf49fec809c */
      {
        SDY1_specification_Graduation_element_G_Angle_mod(pContext) = (SGLfloat_gt(SDY1_specification_Graduation_element_G_Angle(pContext), 720.0F) ? SGLfloat_sub(SDY1_specification_Graduation_element_G_Angle(pContext), 720.0F) : (SGLfloat_gt(SDY1_specification_Graduation_element_G_Angle(pContext), 360.0F) ? SGLfloat_sub(SDY1_specification_Graduation_element_G_Angle(pContext), 360.0F) : (SGLfloat_gt(SDY1_specification_Graduation_element_G_Angle(pContext), 0.0F) ? SDY1_specification_Graduation_element_G_Angle(pContext) : (SGLfloat_gt(SDY1_specification_Graduation_element_G_Angle(pContext), -360.0F) ? SGLfloat_add(SDY1_specification_Graduation_element_G_Angle(pContext), 360.0F) : SGLfloat_add(SDY1_specification_Graduation_element_G_Angle(pContext), 720.0F)))));
      }

      /* Object: shape, Type: shape, OID: de65e72f-c22f-4b28-a9be-7cf74d875d1a */
      {
        if (SGLint32_ge(SDY1_specification_Graduation_element_G_FontColor(pContext), 0L)) {
          /* color object part */
          f013(SDY1_specification_Graduation_element_G_FontColor(pContext));
          f009(f224);
          f008(f148);
          f036(255L);
          f009(f167);
          f009(f230);
          /* fill object part */
          f009(f227);
          f001(f109);
          f035(SGLfloat_add(SDY1_specification_Graduation_element_G_Size(pContext), SDY1_specification_Graduation_element_G_OriginOffset(pContext)), 0.5F);
          f035(SGLfloat_add(SDY1_specification_Graduation_element_G_Size(pContext), SDY1_specification_Graduation_element_G_OriginOffset(pContext)), -0.5F);
          f035(SDY1_specification_Graduation_element_G_OriginOffset(pContext), -0.5F);
          f035(SDY1_specification_Graduation_element_G_OriginOffset(pContext), 0.5F);
          f002();
        }
      }

      /* Object: group, Type: container, OID: a5777963-01da-43d7-a7c1-07fc86e94971 */
      {
        f019();
        f027(SGLfloat_add(SGLfloat_add(SDY1_specification_Graduation_element_G_Size(pContext), SDY1_specification_Graduation_element_G_OriginOffset(pContext)), 5.0F), 0.0F);
        f022(SGLfloat_neg(SDY1_specification_Graduation_element_G_Angle_mod(pContext)));

        /* Object: group_1, Type: container, OID: 26a836ae-166f-4a9f-af86-ffc0d3b288e6 */
        {

          /* Object: bi_font, Type: bifont, OID: df81af13-2b7e-4361-bd5d-173ff8add996 */
          {
            if (SGLint32_ge(SDY1_specification_Graduation_element_G_FontColor(pContext), 0L)) {
              f013(SDY1_specification_Graduation_element_G_FontColor(pContext));
              f085(-1L);
              f075(2L);
              f048(SDY1_specification_Graduation_element_G_Font(pContext));
              f009(f150);
              f050((SGLfloat_lt(SDY1_specification_Graduation_element_G_Angle_mod(pContext), 70.0F) ? 0L : (SGLfloat_lt(SDY1_specification_Graduation_element_G_Angle_mod(pContext), 110.0F) ? 1L : (SGLfloat_lt(SDY1_specification_Graduation_element_G_Angle_mod(pContext), 250.0F) ? 2L : (SGLfloat_lt(SDY1_specification_Graduation_element_G_Angle_mod(pContext), 290.0F) ? 1L : 0L)))), (SGLfloat_lt(SDY1_specification_Graduation_element_G_Angle_mod(pContext), 20.0F) ? 1L : (SGLfloat_lt(SDY1_specification_Graduation_element_G_Angle_mod(pContext), 160.0F) ? 0L : (SGLfloat_lt(SDY1_specification_Graduation_element_G_Angle_mod(pContext), 200.0F) ? 1L : (SGLfloat_lt(SDY1_specification_Graduation_element_G_Angle_mod(pContext), 340.0F) ? 2L : 1L)))));
              f049(SDY1_specification_Graduation_element_G_FontColor(pContext), SDY1_specification_Graduation_element_G_Font(pContext), 2L);
              {
                sgl_numeric_format lFormat;
                lFormat.l_integralPart = SDY1_specification_Graduation_element_G_Integral(pContext);
                lFormat.l_fractionalPart = SDY1_specification_Graduation_element_G_Fractional(pContext);
                lFormat.l_secondFontPos = 1L;
                lFormat.b_separator = 46U;
                lFormat.b_leadingZeros = 0;
                lFormat.l_displaySign = f203;
                f054(0.0F, 0.0F, SDY1_specification_Graduation_element_G_Value(pContext), &lFormat);
              }
            }
          }
        }
        f020();
      }
      f020();
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2018-01-13T10:58:27
 *********************************************************/

