/*********************************************************
 **
 ** File  SDY1_specification_PushButton.h
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\PushButton.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2018-01-13T10:58:26
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY1_specification\Code -prefix SDY1_specification_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\InfiniteKnob.wgfx
 *********************************************************/

/* Inlined constants:
   FOCUS_WIDTH=3.4
   INNERBORDER_WIDTH=0.6
   OUTLINE_RADIUS=8.0
   TEXT_MARGIN=5.0
   WL_BACK1=2
   WL_BLACK=1
   WL_DISABLE_ALPHA=11
   WL_FOCUS=14
   WL_INNER=9
   WL_TEXT_UNSEL=13
 */

#ifndef SDY1_SPECIFICATION_PUSHBUTTON_H
#define SDY1_SPECIFICATION_PUSHBUTTON_H

#include "sgl_types.h"
#include "kcg_assign.h"

#include "SDY1_specification_IndividualFocus.h"
#include "SDY1_specification_KeyEvent.h"
#include "SDY1_specification_ColorBase.h"
#include "SDY1_specification_FrameShape.h"
#include "SDY1_specification_ClippedLabel.h"
#include "wrapper_PushButton_mem.h"

/* Accessors */
#define SDY1_specification_PushButton_G_WidgetId(_C_) (_C_)->WidgetId
#define SDY1_specification_PushButton_S_WidgetId(_C_,_V_) (_C_)->WidgetId = (_V_)
#define SDY1_specification_PushButton_G_NextWidgetId(_C_) (_C_)->NextWidgetId
#define SDY1_specification_PushButton_S_NextWidgetId(_C_,_V_) (_C_)->NextWidgetId = (_V_)
#define SDY1_specification_PushButton_G_SizeX(_C_) (_C_)->SizeX
#define SDY1_specification_PushButton_S_SizeX(_C_,_V_) (_C_)->SizeX = (_V_)
#define SDY1_specification_PushButton_G_SizeY(_C_) (_C_)->SizeY
#define SDY1_specification_PushButton_S_SizeY(_C_,_V_) (_C_)->SizeY = (_V_)
#define SDY1_specification_PushButton_G_Enable(_C_) (_C_)->Enable
#define SDY1_specification_PushButton_S_Enable(_C_,_V_) (_C_)->Enable = (_V_)
#define SDY1_specification_PushButton_G_Style(_C_) (_C_)->Style
#define SDY1_specification_PushButton_S_Style(_C_,_V_) (_C_)->Style = (_V_)
#define SDY1_specification_PushButton_G_ColorStyle(_C_) (_C_)->ColorStyle
#define SDY1_specification_PushButton_S_ColorStyle(_C_,_V_) (_C_)->ColorStyle = (_V_)
#define SDY1_specification_PushButton_G_LabelString(_C_) (*(_C_)->LabelString)
#define SDY1_specification_PushButton_S_LabelString(_C_,_V_) (_C_)->LabelString = &(_V_)
#define SDY1_specification_PushButton_G_ButtonColor(_C_) (_C_)->ButtonColor
#define SDY1_specification_PushButton_S_ButtonColor(_C_,_V_) (_C_)->ButtonColor = (_V_)
#define SDY1_specification_PushButton_G_Font(_C_) (_C_)->Font
#define SDY1_specification_PushButton_S_Font(_C_,_V_) (_C_)->Font = (_V_)
#define SDY1_specification_PushButton_G_TextColor(_C_) (_C_)->TextColor
#define SDY1_specification_PushButton_S_TextColor(_C_,_V_) (_C_)->TextColor = (_V_)
#define SDY1_specification_PushButton_G_TextAlignment(_C_) (_C_)->TextAlignment
#define SDY1_specification_PushButton_S_TextAlignment(_C_,_V_) (_C_)->TextAlignment = (_V_)
#define SDY1_specification_PushButton_G_EmitCondition(_C_) (_C_)->EmitCondition
#define SDY1_specification_PushButton_S_EmitCondition(_C_,_V_) (_C_)->EmitCondition = (_V_)
#define SDY1_specification_PushButton_G_Selection(_C_) (_C_)->Selection
#define SDY1_specification_PushButton_S_Selection(_C_,_V_) (_C_)->Selection = (_V_)
#define SDY1_specification_PushButton_G_MouseInside(_C_) (_C_)->MouseInside
#define SDY1_specification_PushButton_S_MouseInside(_C_,_V_) (_C_)->MouseInside = (_V_)
#define SDY1_specification_PushButton_G_MouseReleased(_C_) (_C_)->MouseReleased
#define SDY1_specification_PushButton_S_MouseReleased(_C_,_V_) (_C_)->MouseReleased = (_V_)
#define SDY1_specification_PushButton_G_MousePressed(_C_) (_C_)->MousePressed
#define SDY1_specification_PushButton_S_MousePressed(_C_,_V_) (_C_)->MousePressed = (_V_)
#define SDY1_specification_PushButton_G_ButtonPressed(_C_) (_C_)->ButtonPressed
#define SDY1_specification_PushButton_S_ButtonPressed(_C_,_V_) (_C_)->ButtonPressed = (_V_)
#define SDY1_specification_PushButton_G_HasFocus(_C_) (_C_)->HasFocus
#define SDY1_specification_PushButton_S_HasFocus(_C_,_V_) (_C_)->HasFocus = (_V_)
#define SDY1_specification_PushButton_G_KeyCode(_C_) (_C_)->KeyCode
#define SDY1_specification_PushButton_S_KeyCode(_C_,_V_) (_C_)->KeyCode = (_V_)
#define SDY1_specification_PushButton_G_KeyReleased(_C_) (_C_)->KeyReleased
#define SDY1_specification_PushButton_S_KeyReleased(_C_,_V_) (_C_)->KeyReleased = (_V_)
#define SDY1_specification_PushButton_G_KeyPressed(_C_) (_C_)->KeyPressed
#define SDY1_specification_PushButton_S_KeyPressed(_C_,_V_) (_C_)->KeyPressed = (_V_)
#define SDY1_specification_PushButton_G_BaseColor(_C_) (_C_)->BaseColor
#define SDY1_specification_PushButton_S_BaseColor(_C_,_V_) (_C_)->BaseColor = (_V_)
#define SDY1_specification_PushButton_G_LocTextColorUnselected(_C_) (_C_)->LocTextColorUnselected
#define SDY1_specification_PushButton_S_LocTextColorUnselected(_C_,_V_) (_C_)->LocTextColorUnselected = (_V_)
#define SDY1_specification_PushButton_G_LocOuterColor(_C_) (_C_)->LocOuterColor
#define SDY1_specification_PushButton_S_LocOuterColor(_C_,_V_) (_C_)->LocOuterColor = (_V_)
#define SDY1_specification_PushButton_G_LocInnerColor(_C_) (_C_)->LocInnerColor
#define SDY1_specification_PushButton_S_LocInnerColor(_C_,_V_) (_C_)->LocInnerColor = (_V_)
#define SDY1_specification_PushButton_G_LocBackColor(_C_) (_C_)->LocBackColor
#define SDY1_specification_PushButton_S_LocBackColor(_C_,_V_) (_C_)->LocBackColor = (_V_)
#define SDY1_specification_PushButton_G_LocGradColor(_C_) (_C_)->LocGradColor
#define SDY1_specification_PushButton_S_LocGradColor(_C_,_V_) (_C_)->LocGradColor = (_V_)
#define SDY1_specification_PushButton_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct SDY1_specification_typ_PushButton_ {
  /* ------------------------- inputs --------------------------- */
  SGLint32 WidgetId;
  SGLint32 NextWidgetId;
  SGLfloat SizeX;
  SGLfloat SizeY;
  SGLbool Enable;
  SGLint32 Style;
  SGLint32 ColorStyle;
  SGLuint8 (*LabelString)[255UL];
  SGLint32 ButtonColor;
  SGLint32 Font;
  SGLint32 TextColor;
  SGLint32 TextAlignment;
  SGLint32 EmitCondition;
  /* ------------------------- outputs -------------------------- */
  SGLbool Selection;
  /* ------------------------- locals --------------------------- */
  SGLbool MouseInside;
  SGLbool MouseReleased;
  SGLbool MousePressed;
  SGLbool ButtonPressed;
  SGLint32 HasFocus;
  SGLint32 KeyCode;
  SGLbool KeyReleased;
  SGLbool KeyPressed;
  SGLint32 BaseColor;
  SGLint32 LocTextColorUnselected;
  SGLint32 LocOuterColor;
  SGLint32 LocInnerColor;
  SGLint32 LocBackColor;
  SGLint32 LocGradColor;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
  /* ------------------------- subcontexts ---------------------- */
  SDY1_specification_typ_IndividualFocus _IndividualFocus__;
  SDY1_specification_typ_KeyEvent _KeyEvent__;
  wrapper_PushButton_mem _wrapper_PushButton__;
} SDY1_specification_typ_PushButton;

/* Associated functions */
extern void SDY1_specification_PushButton_init(SDY1_specification_typ_PushButton *pContext);
extern void SDY1_specification_PushButton_predraw(SDY1_specification_typ_PushButton *pContext);
extern void SDY1_specification_PushButton_draw(SDY1_specification_typ_PushButton *pContext, SGLint32 pPriority);
extern SDY1_specification_typ_PushButton * SDY1_specification_PushButton_alloc(void);
extern void SDY1_specification_PushButton_free(SDY1_specification_typ_PushButton *pContext);

#endif /* SDY1_SPECIFICATION_PUSHBUTTON_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-13T10:58:26
 *********************************************************/

