/*********************************************************
 **
 ** File  SDY1_specification_Scale.c
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Scale.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2018-01-13T10:58:26
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY1_specification\Code -prefix SDY1_specification_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\InfiniteKnob.wgfx
 *********************************************************/

#include "SDY1_specification_Scale.h"
#include "SDY1_specification_imported_functions.h"
#include "sgl_simu.h"


#include <stdlib.h>
#include <string.h>

SDY1_specification_typ_Scale * SDY1_specification_Scale_alloc(void)
{
  SDY1_specification_typ_Scale *lContext = malloc(sizeof(SDY1_specification_typ_Scale));
  memset(lContext, 0L, sizeof(SDY1_specification_typ_Scale));
  return lContext;
}

void SDY1_specification_Scale_free(SDY1_specification_typ_Scale *pContext)
{
  free(pContext);
}


void SDY1_specification_Scale_init(SDY1_specification_typ_Scale *pContext)
{
  SDY1_specification_Scale_S_Length(pContext, 250.0F);
  SDY1_specification_Scale_S_Width(pContext, 10.0F);
  SDY1_specification_Scale_S_Angle(pContext, 60.0F);
  SDY1_specification_Scale_S_Value(pContext, 50.0F);
  SDY1_specification_Scale_S_Range(pContext, 100.0F);
  SDY1_specification_Scale_S_TextColor(pContext, 2L);
  SDY1_specification_Scale_S_Font(pContext, 21L);
  SDY1_specification_Scale_S_DistLargeGrad(pContext, 0.0F);
  SDY1_specification_Scale_S_NumberOfSmallGradPerLargeGrad(pContext, 5L);
  SDY1_specification_Scale_S_InvertTextSide(pContext, 0);
  SDY1_specification_Scale_S_Integral(pContext, 7L);
  SDY1_specification_Scale_S_Fractional(pContext, 1L);
  {
    static SGLfloat lArray0[60UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    SDY1_specification_Scale_S_PosLargePx(pContext, lArray0);
  }
  {
    static SGLfloat lArray0[60UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    SDY1_specification_Scale_S_ValueNb(pContext, lArray0);
  }
  {
    static SGLfloat lArray0[120UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    SDY1_specification_Scale_S_PosSmallPx(pContext, lArray0);
  }
  SDY1_specification_Scale_S_RunTimeMode(pContext, 0);
  {
    static SGLbool lArray0[60UL] = {1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    SDY1_specification_Scale_S_LargeVisible(pContext, lArray0);
  }
  {
    static SGLbool lArray0[120UL] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    SDY1_specification_Scale_S_SmallVisible(pContext, lArray0);
  }
  SDY1_specification_Scale_S_MinMaxModeActive(pContext, 0);
  SDY1_specification_Scale_S_FontSizeX(pContext, 0.0F);
  SDY1_specification_Scale_S_FontSizeY(pContext, 0.0F);

  pContext->_parentPriority = 0L;

}

void SDY1_specification_Scale_predraw(SDY1_specification_typ_Scale *pContext)
{
  SDY1_specification_Scale_S_Integral(pContext, 7L);
  SDY1_specification_Scale_S_Fractional(pContext, 1L);
  {
    static SGLfloat lArray0[60UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    SDY1_specification_Scale_S_PosLargePx(pContext, lArray0);
  }
  {
    static SGLfloat lArray0[60UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    SDY1_specification_Scale_S_ValueNb(pContext, lArray0);
  }
  {
    static SGLfloat lArray0[120UL] = {0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
    SDY1_specification_Scale_S_PosSmallPx(pContext, lArray0);
  }
  SDY1_specification_Scale_S_RunTimeMode(pContext, 0);
  {
    static SGLbool lArray0[60UL] = {1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    SDY1_specification_Scale_S_LargeVisible(pContext, lArray0);
  }
  {
    static SGLbool lArray0[120UL] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    SDY1_specification_Scale_S_SmallVisible(pContext, lArray0);
  }

}

void SDY1_specification_Scale_draw(SDY1_specification_typ_Scale *pContext, SGLint32 pPriority)
{
  SGLuint32 _lParentMasks = f065();
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: Graduation, Type: container, OID: 4729f8e9-3a51-4d47-a3b6-ded7a660fcbf */
    {

      /* Object: MinMaxMode, Type: assignment, OID: cb98edd9-309e-4fe9-abf6-06bcc8539913 */
      {
        SDY1_specification_Scale_G_MinMaxModeActive(pContext) = SGLfloat_eq(SDY1_specification_Scale_G_DistLargeGrad(pContext), SDY1_specification_Scale_G_Range(pContext));
      }

      /* Object: GetFontSize, Type: importedFunction, OID: bbbfea5b-dfb9-4505-8e45-e00134a6709a */
      {
        f019();
        GetFontSize_Strings(SDY1_specification_Scale_G_Font(pContext), &(SDY1_specification_Scale_G_FontSizeX(pContext)), &(SDY1_specification_Scale_G_FontSizeY(pContext)));
        f064();
        f020();
      }

      /* Object: wrapper_Scale, Type: importedFunction, OID: 287a7685-e6ef-4c5f-872b-0339570ea94d */
      {
        f056(_lParentMasks);
        wrapper_Scale(SDY1_specification_Scale_G_Length(pContext), SDY1_specification_Scale_G_Value(pContext), SDY1_specification_Scale_G_Range(pContext), SDY1_specification_Scale_G_FontSizeX(pContext), SDY1_specification_Scale_G_DistLargeGrad(pContext), SDY1_specification_Scale_G_NumberOfSmallGradPerLargeGrad(pContext), &(SDY1_specification_Scale_G_PosLargePx(pContext)), &(SDY1_specification_Scale_G_PosSmallPx(pContext)), &(SDY1_specification_Scale_G_ValueNb(pContext)), &(SDY1_specification_Scale_G_Integral(pContext)), &(SDY1_specification_Scale_G_Fractional(pContext)), &(SDY1_specification_Scale_G_LargeVisible(pContext)), &(SDY1_specification_Scale_G_SmallVisible(pContext)), &(SDY1_specification_Scale_G_RunTimeMode(pContext)));
      }

      /* Object: MinMaxMode_1, Type: container, OID: 2c75becb-12f5-4676-b388-67c8f662d651 */
      {
        if (SDY1_specification_Scale_G_MinMaxModeActive(pContext)) {
          f019();
          f022(SDY1_specification_Scale_G_Angle(pContext));

          /* Object: MinMax, Type: nplicatorContainer, OID: 901f4ae0-0fdc-41fd-a21f-152fa55d715f */
          {
            SGLfloat lArray0_MinMax[2UL];
            SGLfloat lArray1_MinMax[2UL];
            lArray0_MinMax[0UL] = 0.0F;
            lArray0_MinMax[1UL] = SDY1_specification_Scale_G_Length(pContext);
            lArray1_MinMax[0UL] = SGLfloat_sub(SDY1_specification_Scale_G_Value(pContext), SGLfloat_div(SDY1_specification_Scale_G_Range(pContext), 2.0F));
            lArray1_MinMax[1UL] = SGLfloat_add(SDY1_specification_Scale_G_Value(pContext), SGLfloat_div(SDY1_specification_Scale_G_Range(pContext), 2.0F));
            /* Instances 0 to 1 */
            {
              SGLuint32 _lInstance;
              for (_lInstance=0UL; _lInstance<=1UL; _lInstance++) {
                f056(_lParentMasks);
                f019();
                f027(lArray0_MinMax[_lInstance], 0.0F);
                f022((SDY1_specification_Scale_G_InvertTextSide(pContext) ? 90.0F : 270.0F));
                {
                  SDY1_specification_typ_Scale_element _lSubContextVar;
                  SDY1_specification_typ_Scale_element *_lSubContext = &_lSubContextVar;
                  SDY1_specification_Scale_element_init(_lSubContext);
                  SDY1_specification_Scale_element_S_Angle(_lSubContext, SGLfloat_add(SGLfloat_neg(SDY1_specification_Scale_G_Angle(pContext)), (SDY1_specification_Scale_G_InvertTextSide(pContext) ? (SGLfloat_lt(SDY1_specification_Scale_G_Angle(pContext), 270.0F) ? 270.0F : 630.0F) : (SGLfloat_lt(SDY1_specification_Scale_G_Angle(pContext), 90.0F) ? 90.0F : 450.0F))));
                  SDY1_specification_Scale_element_S_DisplayValue(_lSubContext, 1);
                  SDY1_specification_Scale_element_S_Font(_lSubContext, SDY1_specification_Scale_G_Font(pContext));
                  SDY1_specification_Scale_element_S_FontColor(_lSubContext, SDY1_specification_Scale_G_TextColor(pContext));
                  SDY1_specification_Scale_element_S_Fractional(_lSubContext, SDY1_specification_Scale_G_Fractional(pContext));
                  SDY1_specification_Scale_element_S_GradColor(_lSubContext, SDY1_specification_Scale_G_TextColor(pContext));
                  SDY1_specification_Scale_element_S_Integral(_lSubContext, SDY1_specification_Scale_G_Integral(pContext));
                  SDY1_specification_Scale_element_S_OriginOffset(_lSubContext, 0.0F);
                  SDY1_specification_Scale_element_S_Size(_lSubContext, SDY1_specification_Scale_G_Width(pContext));
                  SDY1_specification_Scale_element_S_Style(_lSubContext, 2L);
                  SDY1_specification_Scale_element_S_Value(_lSubContext, lArray1_MinMax[_lInstance]);
                  _lSubContext->_parentPriority = pContext->_parentPriority;
                  SDY1_specification_Scale_element_draw(_lSubContext, pPriority);
                }
                f020();
              }
            }
          }
          f020();
        }
      }

      /* Object: Normal_Mode, Type: container, OID: 21d301a9-4a63-473c-a8f2-14b232bb1da3 */
      {
        if (SGLbool_not(SDY1_specification_Scale_G_MinMaxModeActive(pContext))) {
          f019();
          f022(SDY1_specification_Scale_G_Angle(pContext));

          /* Object: small, Type: nplicatorContainer, OID: 947898c3-1897-4fe3-bcdb-b787bcb0a9b3 */
          {
            static SGLbool lArray0_small[120UL] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
            static SGLfloat lArray1_small[120UL] = {0.0F,10.0F,20.0F,30.0F,40.0F,50.0F,60.0F,70.0F,80.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F,0.0F};
            /* Instances 0 to 119 */
            {
              SGLuint32 _lInstance;
              for (_lInstance=0UL; _lInstance<=119UL; _lInstance++) {
                if ((SDY1_specification_Scale_G_RunTimeMode(pContext) ? (SDY1_specification_Scale_G_SmallVisible(pContext))[_lInstance] : lArray0_small[_lInstance])) {
                  f056(_lParentMasks);
                  f019();
                  f027((SDY1_specification_Scale_G_PosSmallPx(pContext))[_lInstance], 0.0F);
                  f022((SDY1_specification_Scale_G_InvertTextSide(pContext) ? 90.0F : 270.0F));
                  {
                    SDY1_specification_typ_Scale_element _lSubContextVar;
                    SDY1_specification_typ_Scale_element *_lSubContext = &_lSubContextVar;
                    SDY1_specification_Scale_element_init(_lSubContext);
                    SDY1_specification_Scale_element_S_Angle(_lSubContext, SGLfloat_add(SGLfloat_neg(SDY1_specification_Scale_G_Angle(pContext)), (SDY1_specification_Scale_G_InvertTextSide(pContext) ? (SGLfloat_gt(SDY1_specification_Scale_G_Angle(pContext), 180.0F) ? 540.0F : 180.0F) : (SGLfloat_lt(SDY1_specification_Scale_G_Angle(pContext), 0.0F) ? 0.0F : 360.0F))));
                    SDY1_specification_Scale_element_S_DisplayValue(_lSubContext, 0);
                    SDY1_specification_Scale_element_S_Font(_lSubContext, SDY1_specification_Scale_G_Font(pContext));
                    SDY1_specification_Scale_element_S_FontColor(_lSubContext, SDY1_specification_Scale_G_TextColor(pContext));
                    SDY1_specification_Scale_element_S_Fractional(_lSubContext, SDY1_specification_Scale_G_Fractional(pContext));
                    SDY1_specification_Scale_element_S_GradColor(_lSubContext, SDY1_specification_Scale_G_TextColor(pContext));
                    SDY1_specification_Scale_element_S_Integral(_lSubContext, SDY1_specification_Scale_G_Integral(pContext));
                    SDY1_specification_Scale_element_S_OriginOffset(_lSubContext, 0.0F);
                    SDY1_specification_Scale_element_S_Size(_lSubContext, SGLfloat_div(SDY1_specification_Scale_G_Width(pContext), 2.0F));
                    SDY1_specification_Scale_element_S_Style(_lSubContext, 2L);
                    SDY1_specification_Scale_element_S_Value(_lSubContext, lArray1_small[_lInstance]);
                    _lSubContext->_parentPriority = pContext->_parentPriority;
                    SDY1_specification_Scale_element_draw(_lSubContext, pPriority);
                  }
                  f020();
                }
              }
            }
          }

          /* Object: all, Type: nplicatorContainer, OID: 28225fdb-e8d8-448b-ae29-66b4bc15788a */
          {
            SGLfloat lArray0_all[60UL];
            SGLfloat lArray1_all[60UL];
            lArray0_all[0UL] = 0.0F;
            lArray0_all[1UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 0.1F);
            lArray0_all[2UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 0.2F);
            lArray0_all[3UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 0.3F);
            lArray0_all[4UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 0.4F);
            lArray0_all[5UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 0.5F);
            lArray0_all[6UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 0.6F);
            lArray0_all[7UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 0.7F);
            lArray0_all[8UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 0.8F);
            lArray0_all[9UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 0.9F);
            lArray0_all[10UL] = SDY1_specification_Scale_G_Length(pContext);
            lArray0_all[11UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[12UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[13UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[14UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[15UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[16UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[17UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[18UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[19UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[20UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[21UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[22UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[23UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[24UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[25UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[26UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[27UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[28UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[29UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[30UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[31UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[32UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[33UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[34UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[35UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[36UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[37UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[38UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[39UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[40UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[41UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[42UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[43UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[44UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[45UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[46UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[47UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[48UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[49UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[50UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[51UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[52UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[53UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[54UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[55UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[56UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[57UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[58UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray0_all[59UL] = SGLfloat_mul(SDY1_specification_Scale_G_Length(pContext), 100.0F);
            lArray1_all[0UL] = SGLfloat_sub(SDY1_specification_Scale_G_Value(pContext), SGLfloat_div(SDY1_specification_Scale_G_Range(pContext), 2.0F));
            lArray1_all[1UL] = SGLfloat_add(SGLfloat_sub(SDY1_specification_Scale_G_Value(pContext), SGLfloat_div(SDY1_specification_Scale_G_Range(pContext), 2.0F)), SGLfloat_mul(SDY1_specification_Scale_G_Range(pContext), 0.1F));
            lArray1_all[2UL] = SGLfloat_add(SGLfloat_sub(SDY1_specification_Scale_G_Value(pContext), SGLfloat_div(SDY1_specification_Scale_G_Range(pContext), 2.0F)), SGLfloat_mul(SDY1_specification_Scale_G_Range(pContext), 0.2F));
            lArray1_all[3UL] = SGLfloat_add(SGLfloat_sub(SDY1_specification_Scale_G_Value(pContext), SGLfloat_div(SDY1_specification_Scale_G_Range(pContext), 2.0F)), SGLfloat_mul(SDY1_specification_Scale_G_Range(pContext), 0.3F));
            lArray1_all[4UL] = SGLfloat_add(SGLfloat_sub(SDY1_specification_Scale_G_Value(pContext), SGLfloat_div(SDY1_specification_Scale_G_Range(pContext), 2.0F)), SGLfloat_mul(SDY1_specification_Scale_G_Range(pContext), 0.4F));
            lArray1_all[5UL] = SGLfloat_add(SGLfloat_sub(SDY1_specification_Scale_G_Value(pContext), SGLfloat_div(SDY1_specification_Scale_G_Range(pContext), 2.0F)), SGLfloat_mul(SDY1_specification_Scale_G_Range(pContext), 0.5F));
            lArray1_all[6UL] = SGLfloat_add(SGLfloat_sub(SDY1_specification_Scale_G_Value(pContext), SGLfloat_div(SDY1_specification_Scale_G_Range(pContext), 2.0F)), SGLfloat_mul(SDY1_specification_Scale_G_Range(pContext), 0.6F));
            lArray1_all[7UL] = SGLfloat_add(SGLfloat_sub(SDY1_specification_Scale_G_Value(pContext), SGLfloat_div(SDY1_specification_Scale_G_Range(pContext), 2.0F)), SGLfloat_mul(SDY1_specification_Scale_G_Range(pContext), 0.7F));
            lArray1_all[8UL] = SGLfloat_add(SGLfloat_sub(SDY1_specification_Scale_G_Value(pContext), SGLfloat_div(SDY1_specification_Scale_G_Range(pContext), 2.0F)), SGLfloat_mul(SDY1_specification_Scale_G_Range(pContext), 0.8F));
            lArray1_all[9UL] = SGLfloat_add(SGLfloat_sub(SDY1_specification_Scale_G_Value(pContext), SGLfloat_div(SDY1_specification_Scale_G_Range(pContext), 2.0F)), SGLfloat_mul(SDY1_specification_Scale_G_Range(pContext), 0.9F));
            lArray1_all[10UL] = SGLfloat_add(SGLfloat_sub(SDY1_specification_Scale_G_Value(pContext), SGLfloat_div(SDY1_specification_Scale_G_Range(pContext), 2.0F)), SDY1_specification_Scale_G_Range(pContext));
            lArray1_all[11UL] = 0.0F;
            lArray1_all[12UL] = 0.0F;
            lArray1_all[13UL] = 0.0F;
            lArray1_all[14UL] = 0.0F;
            lArray1_all[15UL] = 0.0F;
            lArray1_all[16UL] = 0.0F;
            lArray1_all[17UL] = 0.0F;
            lArray1_all[18UL] = 0.0F;
            lArray1_all[19UL] = 0.0F;
            lArray1_all[20UL] = 0.0F;
            lArray1_all[21UL] = 0.0F;
            lArray1_all[22UL] = 0.0F;
            lArray1_all[23UL] = 0.0F;
            lArray1_all[24UL] = 0.0F;
            lArray1_all[25UL] = 0.0F;
            lArray1_all[26UL] = 0.0F;
            lArray1_all[27UL] = 0.0F;
            lArray1_all[28UL] = 0.0F;
            lArray1_all[29UL] = 0.0F;
            lArray1_all[30UL] = 0.0F;
            lArray1_all[31UL] = 0.0F;
            lArray1_all[32UL] = 0.0F;
            lArray1_all[33UL] = 0.0F;
            lArray1_all[34UL] = 0.0F;
            lArray1_all[35UL] = 0.0F;
            lArray1_all[36UL] = 0.0F;
            lArray1_all[37UL] = 0.0F;
            lArray1_all[38UL] = 0.0F;
            lArray1_all[39UL] = 0.0F;
            lArray1_all[40UL] = 0.0F;
            lArray1_all[41UL] = 0.0F;
            lArray1_all[42UL] = 0.0F;
            lArray1_all[43UL] = 0.0F;
            lArray1_all[44UL] = 0.0F;
            lArray1_all[45UL] = 0.0F;
            lArray1_all[46UL] = 0.0F;
            lArray1_all[47UL] = 0.0F;
            lArray1_all[48UL] = 0.0F;
            lArray1_all[49UL] = 0.0F;
            lArray1_all[50UL] = 0.0F;
            lArray1_all[51UL] = 0.0F;
            lArray1_all[52UL] = 0.0F;
            lArray1_all[53UL] = 0.0F;
            lArray1_all[54UL] = 0.0F;
            lArray1_all[55UL] = 0.0F;
            lArray1_all[56UL] = 0.0F;
            lArray1_all[57UL] = 0.0F;
            lArray1_all[58UL] = 0.0F;
            lArray1_all[59UL] = 0.0F;
            /* Instances 0 to 59 */
            {
              SGLuint32 _lInstance;
              for (_lInstance=0UL; _lInstance<=59UL; _lInstance++) {
                if ((SDY1_specification_Scale_G_LargeVisible(pContext))[_lInstance]) {
                  f056(_lParentMasks);
                  f019();
                  f027((SDY1_specification_Scale_G_RunTimeMode(pContext) ? (SDY1_specification_Scale_G_PosLargePx(pContext))[_lInstance] : lArray0_all[_lInstance]), 0.0F);
                  f022((SDY1_specification_Scale_G_InvertTextSide(pContext) ? 90.0F : 270.0F));
                  {
                    SDY1_specification_typ_Scale_element _lSubContextVar;
                    SDY1_specification_typ_Scale_element *_lSubContext = &_lSubContextVar;
                    SDY1_specification_Scale_element_init(_lSubContext);
                    SDY1_specification_Scale_element_S_Angle(_lSubContext, SGLfloat_add(SGLfloat_neg(SDY1_specification_Scale_G_Angle(pContext)), (SDY1_specification_Scale_G_InvertTextSide(pContext) ? (SGLfloat_lt(SDY1_specification_Scale_G_Angle(pContext), 270.0F) ? 270.0F : 630.0F) : (SGLfloat_lt(SDY1_specification_Scale_G_Angle(pContext), 90.0F) ? 90.0F : 450.0F))));
                    SDY1_specification_Scale_element_S_DisplayValue(_lSubContext, 1);
                    SDY1_specification_Scale_element_S_Font(_lSubContext, SDY1_specification_Scale_G_Font(pContext));
                    SDY1_specification_Scale_element_S_FontColor(_lSubContext, SDY1_specification_Scale_G_TextColor(pContext));
                    SDY1_specification_Scale_element_S_Fractional(_lSubContext, SDY1_specification_Scale_G_Fractional(pContext));
                    SDY1_specification_Scale_element_S_GradColor(_lSubContext, SDY1_specification_Scale_G_TextColor(pContext));
                    SDY1_specification_Scale_element_S_Integral(_lSubContext, SDY1_specification_Scale_G_Integral(pContext));
                    SDY1_specification_Scale_element_S_OriginOffset(_lSubContext, 0.0F);
                    SDY1_specification_Scale_element_S_Size(_lSubContext, SDY1_specification_Scale_G_Width(pContext));
                    SDY1_specification_Scale_element_S_Style(_lSubContext, 2L);
                    if (SDY1_specification_Scale_G_RunTimeMode(pContext)) {
                      SDY1_specification_Scale_element_S_Value(_lSubContext, (SDY1_specification_Scale_G_ValueNb(pContext))[_lInstance]);
                    }
                    else {
                      SDY1_specification_Scale_element_S_Value(_lSubContext, lArray1_all[_lInstance]);
                    }
                    _lSubContext->_parentPriority = pContext->_parentPriority;
                    SDY1_specification_Scale_element_draw(_lSubContext, pPriority);
                  }
                  f020();
                }
              }
            }
          }
          f020();
        }
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2018-01-13T10:58:26
 *********************************************************/

