/*********************************************************
 **
 ** File  SDY1_specification_control_panel.h
 **
 ** Specification File:  C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2018-01-13T10:58:27
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY1_specification\Code -prefix SDY1_specification_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\InfiniteKnob.wgfx
 *********************************************************/

#ifndef SDY1_SPECIFICATION_CONTROL_PANEL_H
#define SDY1_SPECIFICATION_CONTROL_PANEL_H

#include "sgl_types.h"

#include "SDY1_specification_N_StateLED.h"
#include "SDY1_specification_PushButton.h"
#include "SDY1_specification_Gauge.h"
#include "SDY1_specification_NumericDisplay.h"
#include "SDY1_specification_Slider.h"
struct SDY1_specification_typ_InfiniteKnob_;
#include "SDY1_specification_NumericEditBox.h"
#include "SDY1_specification_LED.h"

/* Accessors */
#ifndef SDY1_specification_control_panel_G_x
#define SDY1_specification_control_panel_G_x(_C_) (_C_)->x
#define SDY1_specification_control_panel_S_x(_C_,_V_) (_C_)->x = (_V_)
#endif /* SDY1_specification_control_panel_G_x */
#ifndef SDY1_specification_control_panel_G_y
#define SDY1_specification_control_panel_G_y(_C_) (_C_)->y
#define SDY1_specification_control_panel_S_y(_C_,_V_) (_C_)->y = (_V_)
#endif /* SDY1_specification_control_panel_G_y */
#ifndef SDY1_specification_control_panel_G_v
#define SDY1_specification_control_panel_G_v(_C_) (_C_)->v
#define SDY1_specification_control_panel_S_v(_C_,_V_) (_C_)->v = (_V_)
#endif /* SDY1_specification_control_panel_G_v */
#ifndef SDY1_specification_control_panel_G_alpha
#define SDY1_specification_control_panel_G_alpha(_C_) (_C_)->alpha
#define SDY1_specification_control_panel_S_alpha(_C_,_V_) (_C_)->alpha = (_V_)
#endif /* SDY1_specification_control_panel_G_alpha */
#ifndef SDY1_specification_control_panel_G_led
#define SDY1_specification_control_panel_G_led(_C_) (_C_)->led
#define SDY1_specification_control_panel_S_led(_C_,_V_) (_C_)->led = (_V_)
#endif /* SDY1_specification_control_panel_G_led */
#ifndef SDY1_specification_control_panel_G_TLlight0
#define SDY1_specification_control_panel_G_TLlight0(_C_) (_C_)->TLlight0
#define SDY1_specification_control_panel_S_TLlight0(_C_,_V_) (_C_)->TLlight0 = (_V_)
#endif /* SDY1_specification_control_panel_G_TLlight0 */
#ifndef SDY1_specification_control_panel_G_TLx0
#define SDY1_specification_control_panel_G_TLx0(_C_) (_C_)->TLx0
#define SDY1_specification_control_panel_S_TLx0(_C_,_V_) (_C_)->TLx0 = (_V_)
#endif /* SDY1_specification_control_panel_G_TLx0 */
#ifndef SDY1_specification_control_panel_G_TLy0
#define SDY1_specification_control_panel_G_TLy0(_C_) (_C_)->TLy0
#define SDY1_specification_control_panel_S_TLy0(_C_,_V_) (_C_)->TLy0 = (_V_)
#endif /* SDY1_specification_control_panel_G_TLy0 */
#ifndef SDY1_specification_control_panel_G_TLlight1
#define SDY1_specification_control_panel_G_TLlight1(_C_) (_C_)->TLlight1
#define SDY1_specification_control_panel_S_TLlight1(_C_,_V_) (_C_)->TLlight1 = (_V_)
#endif /* SDY1_specification_control_panel_G_TLlight1 */
#ifndef SDY1_specification_control_panel_G_TLx1
#define SDY1_specification_control_panel_G_TLx1(_C_) (_C_)->TLx1
#define SDY1_specification_control_panel_S_TLx1(_C_,_V_) (_C_)->TLx1 = (_V_)
#endif /* SDY1_specification_control_panel_G_TLx1 */
#ifndef SDY1_specification_control_panel_G_TLy1
#define SDY1_specification_control_panel_G_TLy1(_C_) (_C_)->TLy1
#define SDY1_specification_control_panel_S_TLy1(_C_,_V_) (_C_)->TLy1 = (_V_)
#endif /* SDY1_specification_control_panel_G_TLy1 */
#ifndef SDY1_specification_control_panel_G_TLlight2
#define SDY1_specification_control_panel_G_TLlight2(_C_) (_C_)->TLlight2
#define SDY1_specification_control_panel_S_TLlight2(_C_,_V_) (_C_)->TLlight2 = (_V_)
#endif /* SDY1_specification_control_panel_G_TLlight2 */
#ifndef SDY1_specification_control_panel_G_TLx2
#define SDY1_specification_control_panel_G_TLx2(_C_) (_C_)->TLx2
#define SDY1_specification_control_panel_S_TLx2(_C_,_V_) (_C_)->TLx2 = (_V_)
#endif /* SDY1_specification_control_panel_G_TLx2 */
#ifndef SDY1_specification_control_panel_G_TLy2
#define SDY1_specification_control_panel_G_TLy2(_C_) (_C_)->TLy2
#define SDY1_specification_control_panel_S_TLy2(_C_,_V_) (_C_)->TLy2 = (_V_)
#endif /* SDY1_specification_control_panel_G_TLy2 */
#ifndef SDY1_specification_control_panel_G_TLlight3
#define SDY1_specification_control_panel_G_TLlight3(_C_) (_C_)->TLlight3
#define SDY1_specification_control_panel_S_TLlight3(_C_,_V_) (_C_)->TLlight3 = (_V_)
#endif /* SDY1_specification_control_panel_G_TLlight3 */
#ifndef SDY1_specification_control_panel_G_TLx3
#define SDY1_specification_control_panel_G_TLx3(_C_) (_C_)->TLx3
#define SDY1_specification_control_panel_S_TLx3(_C_,_V_) (_C_)->TLx3 = (_V_)
#endif /* SDY1_specification_control_panel_G_TLx3 */
#ifndef SDY1_specification_control_panel_G_TLy3
#define SDY1_specification_control_panel_G_TLy3(_C_) (_C_)->TLy3
#define SDY1_specification_control_panel_S_TLy3(_C_,_V_) (_C_)->TLy3 = (_V_)
#endif /* SDY1_specification_control_panel_G_TLy3 */
#ifndef SDY1_specification_control_panel_G_TLlight4
#define SDY1_specification_control_panel_G_TLlight4(_C_) (_C_)->TLlight4
#define SDY1_specification_control_panel_S_TLlight4(_C_,_V_) (_C_)->TLlight4 = (_V_)
#endif /* SDY1_specification_control_panel_G_TLlight4 */
#ifndef SDY1_specification_control_panel_G_TLx4
#define SDY1_specification_control_panel_G_TLx4(_C_) (_C_)->TLx4
#define SDY1_specification_control_panel_S_TLx4(_C_,_V_) (_C_)->TLx4 = (_V_)
#endif /* SDY1_specification_control_panel_G_TLx4 */
#ifndef SDY1_specification_control_panel_G_TLy4
#define SDY1_specification_control_panel_G_TLy4(_C_) (_C_)->TLy4
#define SDY1_specification_control_panel_S_TLy4(_C_,_V_) (_C_)->TLy4 = (_V_)
#endif /* SDY1_specification_control_panel_G_TLy4 */
#ifndef SDY1_specification_control_panel_G_ev0
#define SDY1_specification_control_panel_G_ev0(_C_) (_C_)->ev0
#define SDY1_specification_control_panel_S_ev0(_C_,_V_) (_C_)->ev0 = (_V_)
#endif /* SDY1_specification_control_panel_G_ev0 */
#ifndef SDY1_specification_control_panel_G_ev1
#define SDY1_specification_control_panel_G_ev1(_C_) (_C_)->ev1
#define SDY1_specification_control_panel_S_ev1(_C_,_V_) (_C_)->ev1 = (_V_)
#endif /* SDY1_specification_control_panel_G_ev1 */
#ifndef SDY1_specification_control_panel_G_ev2
#define SDY1_specification_control_panel_G_ev2(_C_) (_C_)->ev2
#define SDY1_specification_control_panel_S_ev2(_C_,_V_) (_C_)->ev2 = (_V_)
#endif /* SDY1_specification_control_panel_G_ev2 */
#ifndef SDY1_specification_control_panel_G_ev3
#define SDY1_specification_control_panel_G_ev3(_C_) (_C_)->ev3
#define SDY1_specification_control_panel_S_ev3(_C_,_V_) (_C_)->ev3 = (_V_)
#endif /* SDY1_specification_control_panel_G_ev3 */
#ifndef SDY1_specification_control_panel_G_score_a
#define SDY1_specification_control_panel_G_score_a(_C_) (_C_)->score_a
#define SDY1_specification_control_panel_S_score_a(_C_,_V_) (_C_)->score_a = (_V_)
#endif /* SDY1_specification_control_panel_G_score_a */
#ifndef SDY1_specification_control_panel_G_ev4
#define SDY1_specification_control_panel_G_ev4(_C_) (_C_)->ev4
#define SDY1_specification_control_panel_S_ev4(_C_,_V_) (_C_)->ev4 = (_V_)
#endif /* SDY1_specification_control_panel_G_ev4 */
#ifndef SDY1_specification_control_panel_G_score_b
#define SDY1_specification_control_panel_G_score_b(_C_) (_C_)->score_b
#define SDY1_specification_control_panel_S_score_b(_C_,_V_) (_C_)->score_b = (_V_)
#endif /* SDY1_specification_control_panel_G_score_b */
#ifndef SDY1_specification_control_panel_G_time
#define SDY1_specification_control_panel_G_time(_C_) (_C_)->time
#define SDY1_specification_control_panel_S_time(_C_,_V_) (_C_)->time = (_V_)
#endif /* SDY1_specification_control_panel_G_time */
#ifndef SDY1_specification_control_panel_G_obspres0
#define SDY1_specification_control_panel_G_obspres0(_C_) (_C_)->obspres0
#define SDY1_specification_control_panel_S_obspres0(_C_,_V_) (_C_)->obspres0 = (_V_)
#endif /* SDY1_specification_control_panel_G_obspres0 */
#ifndef SDY1_specification_control_panel_G_obsx0
#define SDY1_specification_control_panel_G_obsx0(_C_) (_C_)->obsx0
#define SDY1_specification_control_panel_S_obsx0(_C_,_V_) (_C_)->obsx0 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsx0 */
#ifndef SDY1_specification_control_panel_G_obsy0
#define SDY1_specification_control_panel_G_obsy0(_C_) (_C_)->obsy0
#define SDY1_specification_control_panel_S_obsy0(_C_,_V_) (_C_)->obsy0 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsy0 */
#ifndef SDY1_specification_control_panel_G_obspres1
#define SDY1_specification_control_panel_G_obspres1(_C_) (_C_)->obspres1
#define SDY1_specification_control_panel_S_obspres1(_C_,_V_) (_C_)->obspres1 = (_V_)
#endif /* SDY1_specification_control_panel_G_obspres1 */
#ifndef SDY1_specification_control_panel_G_obspres2
#define SDY1_specification_control_panel_G_obspres2(_C_) (_C_)->obspres2
#define SDY1_specification_control_panel_S_obspres2(_C_,_V_) (_C_)->obspres2 = (_V_)
#endif /* SDY1_specification_control_panel_G_obspres2 */
#ifndef SDY1_specification_control_panel_G_obspres3
#define SDY1_specification_control_panel_G_obspres3(_C_) (_C_)->obspres3
#define SDY1_specification_control_panel_S_obspres3(_C_,_V_) (_C_)->obspres3 = (_V_)
#endif /* SDY1_specification_control_panel_G_obspres3 */
#ifndef SDY1_specification_control_panel_G_obspres4
#define SDY1_specification_control_panel_G_obspres4(_C_) (_C_)->obspres4
#define SDY1_specification_control_panel_S_obspres4(_C_,_V_) (_C_)->obspres4 = (_V_)
#endif /* SDY1_specification_control_panel_G_obspres4 */
#ifndef SDY1_specification_control_panel_G_obspres5
#define SDY1_specification_control_panel_G_obspres5(_C_) (_C_)->obspres5
#define SDY1_specification_control_panel_S_obspres5(_C_,_V_) (_C_)->obspres5 = (_V_)
#endif /* SDY1_specification_control_panel_G_obspres5 */
#ifndef SDY1_specification_control_panel_G_obspres6
#define SDY1_specification_control_panel_G_obspres6(_C_) (_C_)->obspres6
#define SDY1_specification_control_panel_S_obspres6(_C_,_V_) (_C_)->obspres6 = (_V_)
#endif /* SDY1_specification_control_panel_G_obspres6 */
#ifndef SDY1_specification_control_panel_G_obspres7
#define SDY1_specification_control_panel_G_obspres7(_C_) (_C_)->obspres7
#define SDY1_specification_control_panel_S_obspres7(_C_,_V_) (_C_)->obspres7 = (_V_)
#endif /* SDY1_specification_control_panel_G_obspres7 */
#ifndef SDY1_specification_control_panel_G_obspres8
#define SDY1_specification_control_panel_G_obspres8(_C_) (_C_)->obspres8
#define SDY1_specification_control_panel_S_obspres8(_C_,_V_) (_C_)->obspres8 = (_V_)
#endif /* SDY1_specification_control_panel_G_obspres8 */
#ifndef SDY1_specification_control_panel_G_obspres9
#define SDY1_specification_control_panel_G_obspres9(_C_) (_C_)->obspres9
#define SDY1_specification_control_panel_S_obspres9(_C_,_V_) (_C_)->obspres9 = (_V_)
#endif /* SDY1_specification_control_panel_G_obspres9 */
#ifndef SDY1_specification_control_panel_G_obsx1
#define SDY1_specification_control_panel_G_obsx1(_C_) (_C_)->obsx1
#define SDY1_specification_control_panel_S_obsx1(_C_,_V_) (_C_)->obsx1 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsx1 */
#ifndef SDY1_specification_control_panel_G_obsx2
#define SDY1_specification_control_panel_G_obsx2(_C_) (_C_)->obsx2
#define SDY1_specification_control_panel_S_obsx2(_C_,_V_) (_C_)->obsx2 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsx2 */
#ifndef SDY1_specification_control_panel_G_obsx3
#define SDY1_specification_control_panel_G_obsx3(_C_) (_C_)->obsx3
#define SDY1_specification_control_panel_S_obsx3(_C_,_V_) (_C_)->obsx3 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsx3 */
#ifndef SDY1_specification_control_panel_G_obsx4
#define SDY1_specification_control_panel_G_obsx4(_C_) (_C_)->obsx4
#define SDY1_specification_control_panel_S_obsx4(_C_,_V_) (_C_)->obsx4 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsx4 */
#ifndef SDY1_specification_control_panel_G_obsx5
#define SDY1_specification_control_panel_G_obsx5(_C_) (_C_)->obsx5
#define SDY1_specification_control_panel_S_obsx5(_C_,_V_) (_C_)->obsx5 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsx5 */
#ifndef SDY1_specification_control_panel_G_obsx6
#define SDY1_specification_control_panel_G_obsx6(_C_) (_C_)->obsx6
#define SDY1_specification_control_panel_S_obsx6(_C_,_V_) (_C_)->obsx6 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsx6 */
#ifndef SDY1_specification_control_panel_G_obsx7
#define SDY1_specification_control_panel_G_obsx7(_C_) (_C_)->obsx7
#define SDY1_specification_control_panel_S_obsx7(_C_,_V_) (_C_)->obsx7 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsx7 */
#ifndef SDY1_specification_control_panel_G_obsx8
#define SDY1_specification_control_panel_G_obsx8(_C_) (_C_)->obsx8
#define SDY1_specification_control_panel_S_obsx8(_C_,_V_) (_C_)->obsx8 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsx8 */
#ifndef SDY1_specification_control_panel_G_obsx9
#define SDY1_specification_control_panel_G_obsx9(_C_) (_C_)->obsx9
#define SDY1_specification_control_panel_S_obsx9(_C_,_V_) (_C_)->obsx9 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsx9 */
#ifndef SDY1_specification_control_panel_G_obsy1
#define SDY1_specification_control_panel_G_obsy1(_C_) (_C_)->obsy1
#define SDY1_specification_control_panel_S_obsy1(_C_,_V_) (_C_)->obsy1 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsy1 */
#ifndef SDY1_specification_control_panel_G_obsy2
#define SDY1_specification_control_panel_G_obsy2(_C_) (_C_)->obsy2
#define SDY1_specification_control_panel_S_obsy2(_C_,_V_) (_C_)->obsy2 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsy2 */
#ifndef SDY1_specification_control_panel_G_obsy3
#define SDY1_specification_control_panel_G_obsy3(_C_) (_C_)->obsy3
#define SDY1_specification_control_panel_S_obsy3(_C_,_V_) (_C_)->obsy3 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsy3 */
#ifndef SDY1_specification_control_panel_G_obsy4
#define SDY1_specification_control_panel_G_obsy4(_C_) (_C_)->obsy4
#define SDY1_specification_control_panel_S_obsy4(_C_,_V_) (_C_)->obsy4 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsy4 */
#ifndef SDY1_specification_control_panel_G_obsy5
#define SDY1_specification_control_panel_G_obsy5(_C_) (_C_)->obsy5
#define SDY1_specification_control_panel_S_obsy5(_C_,_V_) (_C_)->obsy5 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsy5 */
#ifndef SDY1_specification_control_panel_G_obsy6
#define SDY1_specification_control_panel_G_obsy6(_C_) (_C_)->obsy6
#define SDY1_specification_control_panel_S_obsy6(_C_,_V_) (_C_)->obsy6 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsy6 */
#ifndef SDY1_specification_control_panel_G_obsy7
#define SDY1_specification_control_panel_G_obsy7(_C_) (_C_)->obsy7
#define SDY1_specification_control_panel_S_obsy7(_C_,_V_) (_C_)->obsy7 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsy7 */
#ifndef SDY1_specification_control_panel_G_obsy8
#define SDY1_specification_control_panel_G_obsy8(_C_) (_C_)->obsy8
#define SDY1_specification_control_panel_S_obsy8(_C_,_V_) (_C_)->obsy8 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsy8 */
#ifndef SDY1_specification_control_panel_G_obsy9
#define SDY1_specification_control_panel_G_obsy9(_C_) (_C_)->obsy9
#define SDY1_specification_control_panel_S_obsy9(_C_,_V_) (_C_)->obsy9 = (_V_)
#endif /* SDY1_specification_control_panel_G_obsy9 */
#ifndef SDY1_specification_control_panel_G_top
#define SDY1_specification_control_panel_G_top(_C_) (_C_)->top
#define SDY1_specification_control_panel_S_top(_C_,_V_) (_C_)->top = (_V_)
#endif /* SDY1_specification_control_panel_G_top */
#ifndef SDY1_specification_control_panel_G_alpha_init
#define SDY1_specification_control_panel_G_alpha_init(_C_) (_C_)->alpha_init
#define SDY1_specification_control_panel_S_alpha_init(_C_,_V_) (_C_)->alpha_init = (_V_)
#endif /* SDY1_specification_control_panel_G_alpha_init */
#ifndef SDY1_specification_control_panel_G_x_init
#define SDY1_specification_control_panel_G_x_init(_C_) (_C_)->x_init
#define SDY1_specification_control_panel_S_x_init(_C_,_V_) (_C_)->x_init = (_V_)
#endif /* SDY1_specification_control_panel_G_x_init */
#ifndef SDY1_specification_control_panel_G_y_init
#define SDY1_specification_control_panel_G_y_init(_C_) (_C_)->y_init
#define SDY1_specification_control_panel_S_y_init(_C_,_V_) (_C_)->y_init = (_V_)
#endif /* SDY1_specification_control_panel_G_y_init */
#ifndef SDY1_specification_control_panel_G_map_id
#define SDY1_specification_control_panel_G_map_id(_C_) (_C_)->map_id
#define SDY1_specification_control_panel_S_map_id(_C_,_V_) (_C_)->map_id = (_V_)
#endif /* SDY1_specification_control_panel_G_map_id */
#ifndef SDY1_specification_control_panel_G_iti_id
#define SDY1_specification_control_panel_G_iti_id(_C_) (_C_)->iti_id
#define SDY1_specification_control_panel_S_iti_id(_C_,_V_) (_C_)->iti_id = (_V_)
#endif /* SDY1_specification_control_panel_G_iti_id */
#ifndef SDY1_specification_control_panel_G_x0
#define SDY1_specification_control_panel_G_x0(_C_) (_C_)->x0
#define SDY1_specification_control_panel_S_x0(_C_,_V_) (_C_)->x0 = (_V_)
#endif /* SDY1_specification_control_panel_G_x0 */
#ifndef SDY1_specification_control_panel_G_y0
#define SDY1_specification_control_panel_G_y0(_C_) (_C_)->y0
#define SDY1_specification_control_panel_S_y0(_C_,_V_) (_C_)->y0 = (_V_)
#endif /* SDY1_specification_control_panel_G_y0 */
#ifndef SDY1_specification_control_panel_G_alpha0
#define SDY1_specification_control_panel_G_alpha0(_C_) (_C_)->alpha0
#define SDY1_specification_control_panel_S_alpha0(_C_,_V_) (_C_)->alpha0 = (_V_)
#endif /* SDY1_specification_control_panel_G_alpha0 */
#ifndef SDY1_specification_control_panel_G_map0
#define SDY1_specification_control_panel_G_map0(_C_) (_C_)->map0
#define SDY1_specification_control_panel_S_map0(_C_,_V_) (_C_)->map0 = (_V_)
#endif /* SDY1_specification_control_panel_G_map0 */
#ifndef SDY1_specification_control_panel_G_iti0
#define SDY1_specification_control_panel_G_iti0(_C_) (_C_)->iti0
#define SDY1_specification_control_panel_S_iti0(_C_,_V_) (_C_)->iti0 = (_V_)
#endif /* SDY1_specification_control_panel_G_iti0 */

/* Context type */
typedef struct SDY1_specification_typ_control_panel_ {
  /* ------------------------- inputs --------------------------- */
  SGLdouble x;
  SGLdouble y;
  SGLdouble v;
  SGLdouble alpha;
  SGLint32 led;
  SGLint32 TLlight0;
  SGLdouble TLx0;
  SGLdouble TLy0;
  SGLint32 TLlight1;
  SGLdouble TLx1;
  SGLdouble TLy1;
  SGLint32 TLlight2;
  SGLdouble TLx2;
  SGLdouble TLy2;
  SGLint32 TLlight3;
  SGLdouble TLx3;
  SGLdouble TLy3;
  SGLint32 TLlight4;
  SGLdouble TLx4;
  SGLdouble TLy4;
  SGLbool ev0;
  SGLbool ev1;
  SGLbool ev2;
  SGLbool ev3;
  SGLint32 score_a;
  SGLbool ev4;
  SGLint32 score_b;
  SGLdouble time;
  SGLbool obspres0;
  SGLdouble obsx0;
  SGLdouble obsy0;
  SGLbool obspres1;
  SGLbool obspres2;
  SGLbool obspres3;
  SGLbool obspres4;
  SGLbool obspres5;
  SGLbool obspres6;
  SGLbool obspres7;
  SGLbool obspres8;
  SGLbool obspres9;
  SGLdouble obsx1;
  SGLdouble obsx2;
  SGLdouble obsx3;
  SGLdouble obsx4;
  SGLdouble obsx5;
  SGLdouble obsx6;
  SGLdouble obsx7;
  SGLdouble obsx8;
  SGLdouble obsx9;
  SGLdouble obsy1;
  SGLdouble obsy2;
  SGLdouble obsy3;
  SGLdouble obsy4;
  SGLdouble obsy5;
  SGLdouble obsy6;
  SGLdouble obsy7;
  SGLdouble obsy8;
  SGLdouble obsy9;
  /* ------------------------- outputs -------------------------- */
  SGLbool top;
  SGLdouble alpha_init;
  SGLdouble x_init;
  SGLdouble y_init;
  SGLint32 map_id;
  SGLint32 iti_id;
  /* ------------------------- locals --------------------------- */
  SGLfloat x0;
  SGLfloat y0;
  SGLfloat alpha0;
  SGLfloat map0;
  SGLfloat iti0;
  /* ------------------------- subcontexts ---------------------- */
  SDY1_specification_typ_N_StateLED _N_StateLED__;
  SDY1_specification_typ_N_StateLED _N_StateLED_1__;
  SDY1_specification_typ_N_StateLED _N_StateLED_2__;
  SDY1_specification_typ_N_StateLED _N_StateLED_3__;
  SDY1_specification_typ_N_StateLED _N_StateLED_4__;
  SDY1_specification_typ_PushButton _PushButton__;
  SDY1_specification_typ_Gauge _GaugeSpeed__;
  SDY1_specification_typ_Slider _SliderX__;
  SDY1_specification_typ_Slider _SliderY__;
  struct SDY1_specification_typ_InfiniteKnob_ *_InfiniteKnobHeading__;
  SDY1_specification_typ_NumericEditBox _NumericEditBoxMap__;
  SDY1_specification_typ_NumericEditBox _NumericEditBoxIti__;
  SDY1_specification_typ_N_StateLED _N_StateLEDStatus__;
  SDY1_specification_typ_LED _LEDevent0__;
  SDY1_specification_typ_LED _LEDevent1__;
  SDY1_specification_typ_LED _LEDevent2__;
  SDY1_specification_typ_LED _LEDevent3__;
  SDY1_specification_typ_LED _LEDevent4__;
} SDY1_specification_typ_control_panel;

/* Associated functions */
extern void SDY1_specification_control_panel_init(SDY1_specification_typ_control_panel *pContext);
extern void SDY1_specification_control_panel_predraw(SDY1_specification_typ_control_panel *pContext);
extern void SDY1_specification_control_panel_draw(SDY1_specification_typ_control_panel *pContext, SGLint32 pPriority);
extern SDY1_specification_typ_control_panel * SDY1_specification_control_panel_alloc(void);
extern void SDY1_specification_control_panel_free(SDY1_specification_typ_control_panel *pContext);

#endif /* SDY1_SPECIFICATION_CONTROL_PANEL_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-13T10:58:27
 *********************************************************/

