/*********************************************************
 **
 ** File  SDY1_specification_ClippedLabel.h
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\ClippedLabel.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2018-01-13T10:58:26
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY1_specification\Code -prefix SDY1_specification_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\InfiniteKnob.wgfx
 *********************************************************/

/* Inlined constants:
   BorderSize=3.0
   InnerBorder=3.0
 */

#ifndef SDY1_SPECIFICATION_CLIPPEDLABEL_H
#define SDY1_SPECIFICATION_CLIPPEDLABEL_H

#include "sgl_types.h"
#include "kcg_assign.h"


/* Accessors */
#define SDY1_specification_ClippedLabel_G_SizeX(_C_) (_C_)->SizeX
#define SDY1_specification_ClippedLabel_S_SizeX(_C_,_V_) (_C_)->SizeX = (_V_)
#define SDY1_specification_ClippedLabel_G_SizeY(_C_) (_C_)->SizeY
#define SDY1_specification_ClippedLabel_S_SizeY(_C_,_V_) (_C_)->SizeY = (_V_)
#define SDY1_specification_ClippedLabel_G_LabelString(_C_) (*(_C_)->LabelString)
#define SDY1_specification_ClippedLabel_S_LabelString(_C_,_V_) (_C_)->LabelString = &(_V_)
#define SDY1_specification_ClippedLabel_G_Font(_C_) (_C_)->Font
#define SDY1_specification_ClippedLabel_S_Font(_C_,_V_) (_C_)->Font = (_V_)
#define SDY1_specification_ClippedLabel_G_TextColor(_C_) (_C_)->TextColor
#define SDY1_specification_ClippedLabel_S_TextColor(_C_,_V_) (_C_)->TextColor = (_V_)
#define SDY1_specification_ClippedLabel_G_Alignment(_C_) (_C_)->Alignment
#define SDY1_specification_ClippedLabel_S_Alignment(_C_,_V_) (_C_)->Alignment = (_V_)
#define SDY1_specification_ClippedLabel_G_AlignmentVertical(_C_) (_C_)->AlignmentVertical
#define SDY1_specification_ClippedLabel_S_AlignmentVertical(_C_,_V_) (_C_)->AlignmentVertical = (_V_)
#define SDY1_specification_ClippedLabel_G_TextType(_C_) (_C_)->TextType
#define SDY1_specification_ClippedLabel_S_TextType(_C_,_V_) (_C_)->TextType = (_V_)
#define SDY1_specification_ClippedLabel_G_BackColor(_C_) (_C_)->BackColor
#define SDY1_specification_ClippedLabel_S_BackColor(_C_,_V_) (_C_)->BackColor = (_V_)
#define SDY1_specification_ClippedLabel_G_TextSizeX(_C_) (_C_)->TextSizeX
#define SDY1_specification_ClippedLabel_S_TextSizeX(_C_,_V_) (_C_)->TextSizeX = (_V_)
#define SDY1_specification_ClippedLabel_G_TextSizeY(_C_) (_C_)->TextSizeY
#define SDY1_specification_ClippedLabel_S_TextSizeY(_C_,_V_) (_C_)->TextSizeY = (_V_)
#define SDY1_specification_ClippedLabel_G_TotalBorder(_C_) (_C_)->TotalBorder
#define SDY1_specification_ClippedLabel_S_TotalBorder(_C_,_V_) (_C_)->TotalBorder = (_V_)
#define SDY1_specification_ClippedLabel_HOOK(_C_,_F_,_D_) 

/* Context type */
typedef struct SDY1_specification_typ_ClippedLabel_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat SizeX;
  SGLfloat SizeY;
  SGLuint8 (*LabelString)[255UL];
  SGLint32 Font;
  SGLint32 TextColor;
  SGLint32 Alignment;
  SGLint32 AlignmentVertical;
  SGLint32 TextType;
  SGLint32 BackColor;
  SGLfloat TextSizeX;
  SGLfloat TextSizeY;
  /* ------------------------- outputs -------------------------- */
  SGLfloat TotalBorder;
  /* ------------------------- parent priority ------------------ */
  SGLint32 _parentPriority;
} SDY1_specification_typ_ClippedLabel;

/* Associated functions */
extern void SDY1_specification_ClippedLabel_init(SDY1_specification_typ_ClippedLabel *pContext);
extern void SDY1_specification_ClippedLabel_predraw(SDY1_specification_typ_ClippedLabel *pContext);
extern void SDY1_specification_ClippedLabel_draw(SDY1_specification_typ_ClippedLabel *pContext, SGLint32 pPriority);
extern SDY1_specification_typ_ClippedLabel * SDY1_specification_ClippedLabel_alloc(void);
extern void SDY1_specification_ClippedLabel_free(SDY1_specification_typ_ClippedLabel *pContext);

#endif /* SDY1_SPECIFICATION_CLIPPEDLABEL_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-13T10:58:26
 *********************************************************/

