/*********************************************************
 **
 ** File  SDY1_specification_IndividualFocus.c
 **
 ** Specification File:  C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\IndividualFocus.wgfx
 **
 ** Automatically generated by SCADE RP Simu
 ** Version 6.6.4 (build i14)
 **
 ** Date of generation: 2018-01-13T10:58:25
 ** Command line: ScadeRPSimu.exe -probes -outdir C:\Users\blagha85\Desktop\PROJET_SCADE\Sync4Students\TheChallenge_KCG66\SDY1_specification\Code -prefix SDY1_specification_ -texturemax 1024 C:\Users\blagha85\Desktop\PROJET_SCADE\RP\specification.rgfx C:\Users\blagha85\Desktop\PROJET_SCADE\RP\texture_table_1.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\textures\Widgets_textures.stt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_fonts.sft C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Styles_colors.sct C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_width.swt C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\Common\Widgets_line_stipple.sst C:\Program Files\ANSYS Inc\v180\SCADE\SCADE Test\Rapid Prototyper\Widgets\InfiniteKnob.wgfx
 *********************************************************/

#include "SDY1_specification_IndividualFocus.h"
#include "SDY1_specification_imported_functions.h"
#include "sgl_simu.h"


#include <stdlib.h>
#include <string.h>

SDY1_specification_typ_IndividualFocus * SDY1_specification_IndividualFocus_alloc(void)
{
  SDY1_specification_typ_IndividualFocus *lContext = malloc(sizeof(SDY1_specification_typ_IndividualFocus));
  memset(lContext, 0L, sizeof(SDY1_specification_typ_IndividualFocus));
  return lContext;
}

void SDY1_specification_IndividualFocus_free(SDY1_specification_typ_IndividualFocus *pContext)
{
  free(pContext);
}


void SDY1_specification_IndividualFocus_init(SDY1_specification_typ_IndividualFocus *pContext)
{
  SDY1_specification_IndividualFocus_S_Requestfocus(pContext, 0);
  SDY1_specification_IndividualFocus_S_RequestNoFocus(pContext, 0);
  SDY1_specification_IndividualFocus_S_NextWidgetId(pContext, 0L);
  SDY1_specification_IndividualFocus_S_IsContainer(pContext, 0);
  SDY1_specification_IndividualFocus_S_WidgetId_in(pContext, 0L);
  SDY1_specification_IndividualFocus_S_HasFocus(pContext, 0L);
  SDY1_specification_IndividualFocus_S_WidgetId(pContext, 0L);
  SDY1_specification_IndividualFocus_S_Pressed(pContext, 0);
  SDY1_specification_IndividualFocus_S_Released(pContext, 0);
  SDY1_specification_IndividualFocus_S_Button(pContext, 0L);
  SDY1_specification_IndividualFocus_S_LocalReleased(pContext, 0);
  SDY1_specification_IndividualFocus_S_PreviousLocalPressed(pContext, 0);
  SDY1_specification_IndividualFocus_S_LocalPressed(pContext, 0);
  SDY1_specification_IndividualFocus_S_PreviousPressed(pContext, 0);
  SDY1_specification_IndividualFocus_S_LocalButton(pContext, 0L);
  SDY1_specification_IndividualFocus_S_isInit(pContext, 1);
  SDY1_specification_IndividualFocus_S_WidgetId_temp(pContext, 0L);

  pContext->_parentPriority = 0L;

  SDY1_specification_Init_init(&(pContext->_Init__));
}

void SDY1_specification_IndividualFocus_predraw(SDY1_specification_typ_IndividualFocus *pContext)
{
  SDY1_specification_IndividualFocus_S_isInit(pContext, 1);

  SDY1_specification_Init_predraw(&(pContext->_Init__));
}

void SDY1_specification_IndividualFocus_draw(SDY1_specification_typ_IndividualFocus *pContext, SGLint32 pPriority)
{
  SGLuint32 _lParentMasks = f065();
  if (SGLint32_eq(pPriority, pContext->_parentPriority)) {

    /* Object: Focus, Type: container, OID: de0c67ea-05d9-4d0b-9de8-5f0c47a1b63c */
    {

      /* Object: GetId, Type: importedFunction, OID: 5e9529d3-a928-4f3f-8411-1246fccf0975 */
      {
        f019();
        GetId(&(SDY1_specification_IndividualFocus_G_WidgetId_temp(pContext)));
        f064();
        f020();
      }

      /* Object: WidgetId, Type: assignment, OID: 9231554c-c2cd-4612-b011-6bbe3f317011 */
      {
        SDY1_specification_IndividualFocus_G_WidgetId(pContext) = (SGLint32_eq(SDY1_specification_IndividualFocus_G_WidgetId_in(pContext), 0L) ? SDY1_specification_IndividualFocus_G_WidgetId_temp(pContext) : SDY1_specification_IndividualFocus_G_WidgetId_in(pContext));
      }

      /* Object: PreviousLocalPressed, Type: assignment, OID: 6f089526-8a3e-4ecc-872e-fb82bc515b9b */
      {
        SDY1_specification_IndividualFocus_G_PreviousLocalPressed(pContext) = SDY1_specification_IndividualFocus_G_LocalPressed(pContext);
      }

      /* Object: PreviousPressed, Type: assignment, OID: 63ba24ae-bd39-47b9-b178-3c54f196790b */
      {
        SDY1_specification_IndividualFocus_G_PreviousPressed(pContext) = SDY1_specification_IndividualFocus_G_Pressed(pContext);
      }

      /* Object: Init, Type: referenceContainer, OID: 8671f389-c3a4-4b13-808f-16a79795b3ac */
      {
        f056(_lParentMasks);
        {
          SDY1_specification_typ_Init *_lSubContext = &(pContext->_Init__);
          _lSubContext->_parentPriority = pContext->_parentPriority;
          SDY1_specification_Init_draw(_lSubContext, pPriority);
          SDY1_specification_IndividualFocus_G_isInit(pContext) = SDY1_specification_Init_G_IsInit(_lSubContext);
        }
      }

      /* Object: ManageIndividualFocus, Type: importedFunction, OID: d339740f-0c33-4cf9-a828-6d6ca3c4a9b5 */
      {
        f056(_lParentMasks);
        f019();
        ManageIndividualFocus(SDY1_specification_IndividualFocus_G_Requestfocus(pContext), SDY1_specification_IndividualFocus_G_RequestNoFocus(pContext), SDY1_specification_IndividualFocus_G_WidgetId(pContext), SDY1_specification_IndividualFocus_G_IsContainer(pContext), SDY1_specification_IndividualFocus_G_NextWidgetId(pContext), SDY1_specification_IndividualFocus_G_isInit(pContext), &(SDY1_specification_IndividualFocus_G_HasFocus(pContext)));
        f064();
        f020();
      }

      /* Object: pointer_event_listener, Type: pointerEvent, OID: bfe2bd31-7368-456d-a1fd-52e95163c997 */
      {
        SDY1_specification_pointer(0L, &(SDY1_specification_IndividualFocus_G_LocalPressed(pContext)), &(SDY1_specification_IndividualFocus_G_LocalReleased(pContext)), &(SDY1_specification_IndividualFocus_G_LocalButton(pContext)), ((void*)0), ((void*)0), ((void*)0));
      }

      /* Object: Pressed, Type: assignment, OID: 6083d933-2d19-4adf-ae18-4571e471fa6c */
      {
        SDY1_specification_IndividualFocus_G_Pressed(pContext) = SGLbool_and(SGLbool_and(SGLint32_ne(SDY1_specification_IndividualFocus_G_HasFocus(pContext), 0L), SGLbool_or(SDY1_specification_IndividualFocus_G_LocalPressed(pContext), SDY1_specification_IndividualFocus_G_PreviousLocalPressed(pContext))), SGLbool_not(SDY1_specification_IndividualFocus_G_PreviousPressed(pContext)));
      }

      /* Object: Released, Type: assignment, OID: 4241469f-f908-4f36-8bd2-9f380a5c2870 */
      {
        SDY1_specification_IndividualFocus_G_Released(pContext) = SGLbool_and(SDY1_specification_IndividualFocus_G_LocalReleased(pContext), SGLint32_ne(SDY1_specification_IndividualFocus_G_HasFocus(pContext), 0L));
      }

      /* Object: Button, Type: assignment, OID: 417caabe-dd47-47be-8eb3-713dbd45f3ab */
      {
        /* On tablet, button will always be 0, so it never changes not matter what events happen.
           On PC, try to keep the button <>0 as long as possible (some events come 1 cycle later than the mouse click) */

        SDY1_specification_IndividualFocus_G_Button(pContext) = (SGLint32_eq(SDY1_specification_IndividualFocus_G_LocalButton(pContext), 0L) ? SDY1_specification_IndividualFocus_G_Button(pContext) : (SGLbool_or(SDY1_specification_IndividualFocus_G_Pressed(pContext), SDY1_specification_IndividualFocus_G_Released(pContext)) ? SDY1_specification_IndividualFocus_G_LocalButton(pContext) : SDY1_specification_IndividualFocus_G_Button(pContext)));
      }
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2018-01-13T10:58:25
 *********************************************************/

